# Copyright (c) 2026, Rupesh P and contributors
# For license information, please see license.txt

"""Seed the Al Taj client list as Customer records.

Run manually; this is deliberately not a patch, so `bench migrate` never
triggers it.

	bench --site <site> execute digitz_erp.seeds.customer_seed.run

	# preview without writing anything
	bench --site <site> execute digitz_erp.seeds.customer_seed.run \
		--kwargs "{'dry_run': 1}"

Taken from "Al Taj Client Details - 2026.xlsx" and held inline, so this runs on
a server with no copy of the spreadsheet.

Two kinds of record, created in this order because the second links to the first:

	PROS    -> customer_type "PRO", one per distinct P.R.O Name
	CLIENTS -> customer_type "Company", linked to their PRO via pro_customer

The sheet's Ref ID column is ignored, as instructed; `Name` is the customer
name, which is also the record name (Customer is autonamed from it).

`company_id` is assigned here rather than left to Customer.before_save. That is
deliberate: before_save only allocates an id when the field is empty, and doing
so also POSTs the customer to the external add_customer_url. Assigning it up
front keeps a bulk import from firing hundreds of calls at the token service.

Re-running is safe: a customer whose name already exists is left untouched.
"""

import re

import frappe
from frappe.utils import cint

CUSTOMER_GROUP = "Default Customer Group"

# The sheet's Email column is free text and holds phone numbers, trailing notes
# and comma-for-dot typos. Frappe rejects those outright, which would cost us
# the whole customer, so anything that is not plainly an address is dropped and
# reported instead.
EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Distinct P.R.O Name values, in the order the sheet first mentions them.
PROS = (
	'Mahmoud Nashaat',
	'Aya Mostafa',
	'Nikhil Raj',
	'Mohammad Alsmadi',
	'Abbas hussein',
	'Abdul Ashfal',
	'Siddique',
	'Noha',
	'AL TAJ',
	'Jithin Raj',
	'Razan Samor',
	'caroline faru',
	'CZG Group',
	'Sabith',
	'Mohammad Hussein Hasan',
	'Zahra',
	'Mahmoud Harara',
	'hazem khalil',
	'Aiban',
	'Rasheed',
	'MOHAMMED OTSMAN',
	'MOHAMED ABDELRAHMAN',
	'ASHIF',
	'Johnson Peter',
	'Dina Ablan',
	'Saif sameh',
	'Gehad',
)

CLIENTS = (
	('TEST CUSTOMER', None, None, '0564089262', None, None),
	('AL NISR AL MUHAJIR TYPING & DOCUMENTS COPYING', 'Mahmoud Nashaat', None, '0585792019', 'alnisralmuhajir@gmail.com', None),
	('Mumahhad Hassan', 'Aya Mostafa', None, '0521633371', None, None),
	('Muhammad Imran', 'Aya Mostafa', None, '971 55 381 7738', 'ruknal2015@gmail.com', None),
	('Rapid Shipping & Logistics', 'Nikhil Raj', None, '+971 50 590 4989', 'transport@rapidgroup.com', None),
	('Gulfsream Arabia Contracting L.L.C', 'Mohammad Alsmadi', None, '971 50 614 9989', None, None),
	('ABBAS HUSSEIN PERSONAL CUSTOMER', 'Abbas hussein', None, '0545949608', None, None),
	('Abdelhadi Engineering & Contracting Co. LLC', 'Mahmoud Nashaat', 'Mr. Kumar Priliant', '0502103812', 'abdelhadieng@gmail.com', None),
	('Abdul Ashfal Personal Customer', 'Abdul Ashfal', None, '0586147816', None, None),
	('ABDULLA & NASIR SUPERMARKET L.L.C', 'Abbas hussein', None, '0582931010', 'hafez_hyper1@gmail.com', None),
	('ABDULLA PRO', 'Siddique', None, '0569979887', 'ABDUKUNNU@GMAIL.COM', None),
	('Abdulrahman Ahmed Advocates and legal', 'Abbas hussein', None, '971561122407', 'Aya.elkhazndar@arlawyers.me', None),
	('ABDULRAHMAN PRO {SUMAYA RESTAURENT}', 'Siddique', None, '0504974518', 'arabdulrahman1786@gmail.com', None),
	('Abed Alabdy Contracting', 'Noha', None, '0558016325', 'acc_ghanem@hotmail.com', None),
	('ABNY BYTK FOR PROJECT MANAGEMENT SERVICES EST.', 'Mahmoud Nashaat', None, '+971 56 930 0343', '0569300343@gmail.com', None),
	('ABRAJ AL BAHAR DOCUMENTS TYPING & COPYING', 'Siddique', None, '0545372505', 'abcdtyping.service@gmail.com', None),
	('ABSHER BUSINESSMEN SERVICES', 'Mahmoud Nashaat', None, '0507572779', 'absherbusinessmenservices@outlook.com', None),
	('AC NELSON (NEILSONIQ)', 'Siddique', 'POST BOX 22525, AL REEM PLAZA , SHARJAH', '0507562485', 'amal.alamiri@nielseniq.com', None),
	('ADC ENERGY SERVICE', 'Aya Mostafa', None, '0586585934', 'aadam@cylingas.ae', None),
	('ADCB BANK', 'AL TAJ', None, '123456', None, None),
	('ADHWA AL MADINAH TYPING CENTER', 'Abbas hussein', None, '0502764987', 'adhwatyping@gmail.com', None),
	('ADVANCED SOLUTIONS Typing & Documents Copying', 'Siddique', None, '0523521448', 'advancedsolutionspro@gmail.com', None),
	('AL EMAN TYPING AND DOCUMENT COPYING', 'Mahmoud Nashaat', None, '0558705085', 'alemantyping@yahoo.com', None),
	('Ajman Freezone Authority', 'Aya Mostafa', None, '971505777065', 'Shamsa.aldhahri@fza.ae', None),
	('Afdhal khidmah typing centre', 'Abbas hussein', None, '0525727690', 'Afdhalkhidmah@gmail.com', None),
	('Al Fares International Tents', 'Aya Mostafa', None, '00971547019683', 'alfaresintl.tent1963@gmail.com', None),
	('Afkar Document & Typing Copying Centre', 'Siddique', None, '0504021337', 'afkartyping123@gmail.com', None),
	('AFLAH TYPING AND DOCUMENT COPYING', 'Siddique', None, '0505490185', 'fahadplk@gmail.com', None),
	('AHLAN TYPING & DOC. COPYING', 'Siddique', None, '97165730315', 'ahlantyping2001@gmail.com', None),
	('AHMED ABDULLAD DOCUMENTS TYPING & COPYING', 'Siddique', None, '0521963294', 'aatyping2018@gmail.com', None),
	('AHMED PRO', 'Siddique', None, '0551026353', 'A.DUDEEN@COREMETAL.NET', None),
	('AJMAL MANAGMENT CONSULTANCY', 'Siddique', None, '0529792313', 'ajmal_amc@hotmail.com', None),
	('AJWAA AL SAHRAA TYPING & DOCUMENT COPYING', 'Siddique', None, '0502154924', 'info@sahraatyping.com', None),
	('Akarem Karam', 'Mahmoud Nashaat', None, '0502297204', None, None),
	('Mr. AKBAR KHAN FARAHI (PRO)', 'Siddique', None, '055 521 8834', 'akbarkhanfarahi@gmail.com', None),
	('Americana Kuwait food company', 'Mahmoud Nashaat', None, '+971 50 561 8585', 'abassiouny@americana-food.com', None),
	('AL AAMEL TYPING AND COPYING SERVICES', 'Siddique', None, '0501590107', 'aameltypingservices08@gmail.com', None),
	('AL AHRAM Business Men Services', 'Abbas hussein', None, '0543078700', 'info@ahramservices.com', None),
	('AL ASAD TYPING & DOCUMENTS COPYING', 'Siddique', None, '0509163552', 'alasadtyping@gmail.com', None),
	('AL ASWAR TYPING AND DOCUMENTS COPYING', 'Abbas hussein', None, '0501864332', 'icasmartserviices@gmail.com', None),
	('AL BAYAN DOCUMENTS TYPING & COPYING', 'Siddique', None, '055334920', 'albayandocuments@gmail.com', None),
	('AL BORJ OIL FIELD MAINTENANCE FIELD SERVICES - L.L.C - S.P.C', 'Jithin Raj', None, '971504651144', 'josephsilvacruz@gmail.com', None),
	('AL BUHAIRA NATIONAL INSURANCE CO BUHAIRA TOWER SHARJAH', 'Siddique', None, '050697488', 'hrdept@albuhaira.com', None),
	('AL DAR DOCUMENTS TYPING & COPYING', 'Siddique', None, '0558180806', 'aldardoctyping@gmail.com', None),
	('Al-Etimad Contracting Company LLC', 'Aya Mostafa', None, '971 567625733', None, None),
	('Al Fadeelah Facility Management Services', 'Aya Mostafa', None, '971550000000', None, None),
	('AL FAHIM TYPING & DOCUMENTS COPYING', 'Siddique', None, '0525846465', 'alfahimtyping@gmail.com', None),
	('AL FARDAN EXCHANGE LLC SP - SHJ .BR. - BRANCH 10', 'Siddique', None, '056507171285', 'm.abdalla@alfardanexchange.com', None),
	('AL FAREED Business men services & doc  clearance', 'Siddique', None, '0529099736', 'alfareedtyping@gmail.com', None),
	('AL FITRAH DOCUMENTS TYPING AND COPYING', 'Siddique', None, '0501291145', 'alfitrah010@gmail.com', None),
	('AL GOWAIR TYPING', 'Siddique', None, '0586871601', 'agtypingcentre@gmail.com', None),
	('AL HADI DOCUMENTS CLEARING SERVICES', 'Abbas hussein', None, '0507622026', 'sales@alhadiae.com', None),
	('AL HADIQAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0559601881', 'alhadiqah2023@gmail.com', None),
	('AL HUDHUD DOCUMENT TYPING & PHOTO COPYING', 'Siddique', None, '0569894606', 'hudhudtyping2022@gmail.com', None),
	('AL ITQAN AL RAQI TYPING AND DOCUMENTS COPYING SERVICES L.L.C', 'Siddique', None, '0508016755', 'alitqanalraqi@gmail.com', None),
	('AL ITQAN AL SAREE TYPING & DOCUMENTS COPYING SERVICES', 'Siddique', None, '0551853372', 'itqanalsareetype2025@gmail.com', None),
	('AL JASR TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0552274966', 'jmshdkunnil353@gmail.com', None),
	('AL JAWHARAH AL WARDIAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0523316145', 'aljawharah7862@gmail.com', None),
	('AL JAZEEL BUSINESS MEN SERVICES', 'Siddique', None, '0564830203', 'jazeelbusiness@gmail.com', None),
	('AL KAHAF TYPING & TRAVEL', 'Siddique', None, '0503265409', 'alkahaftyping@gmail.com', None),
	('AL KALOTI PVT.REAL ESTATE LLC SOLE PROPRIETORSHIP', 'Abbas hussein', None, '0562805706', 'pro@aryanahotels.com', None),
	('AL KHALIL MEAT TR.CO.LLC.', 'Siddique', None, '0508311398', 'elmasedy@alkhalilmeats.com', '100009799600003'),
	('AL KHAT AL JUNOOBI DOCUMENTS TYPING SERVICES', 'Siddique', None, '0503229305', 'alkhataljunoobi@gmail.com', None),
	('AL LABEEB TYPING DOCUMENTS COPYING', 'Siddique', None, '0503562136', 'allabeeb54@gmail.com', None),
	('AL MAIDAN AL SAREE TYPING AND DOCUMENTS PHOTOCOPYING SERVICES L.L.C', 'Siddique', None, '0502060192', 'jamil0320@gmail.com', None),
	('AL MALOMAT AL MUTAKAMLIAH TYPING AND DOCUMENTS COPYING SERVICES', 'Siddique', None, '0553182300', 'farestoulba123@yahoo.com', None),
	('AL MANAF Typing & Doc. copying', 'Siddique', None, '065616919', 'almanaftyping@gmail.com', None),
	('AL MANAR METAL DOORS & WINDOWS FIXING LLC', 'Razan Samor', None, '0555192245', 'bslivetime@gmail.com', None),
	('AL MANARAH INSURANCE COMPANY', 'Siddique', None, '0566161621', None, None),
	('AL MARWAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0506373181', 'almarwa.bs@gmail.com', None),
	('AL MASAH AL ZARQA TYPING & DOCUMENTS COPYING', 'Siddique', None, '0588207386', 'alzarqatc@gmail.com', None),
	('AL MASSA AL HAMRAA TYPING CENTRE', 'Siddique', None, '971502383214', 'almasatyping@gmail.com', None),
	('AL MASSAH AL THAHBIAH DOCUMENTS TYPING & COPYING', 'Siddique', None, '0588793426', 'massah46@gmail.com', None),
	('AL MATAR TYPING AND DOCUMENTS PHOTOCOPYING SERVICES', 'Siddique', None, '0585189698', 'almatartyping@gmail.com', None),
	('AL MAZAYA TYPING & DOCUMENTS COPYING', 'Siddique', None, '0505009372', 'mazayatdc@gmail.com', None),
	('Al Nahdah Documents Clearance', 'Abbas hussein', None, '0552723650', 'alnahdahdocclealance@gmail.com', None),
	('Al Nahrain Security & Safety L L C', 'Mahmoud Nashaat', None, '0504628909', 'Info@alnahrainsafety.com', None),
	('AL NAJEEB TYPING & DOCUMENTS COPYING', 'Siddique', None, '0502336782', 'alnajeebtyping@gmail.com', None),
	('AL NASEEB BUSINESSMEN SERVICES', 'Abbas hussein', None, '0568484190', 'alnaseebajmn@gmail.com', None),
	('AL NASMAH TYPING DOC. COPYING', 'Siddique', None, '0505292712', 'alnasmahtyping00@gmail.com', None),
	('AL NISR AL MASSY TYPING AND DOCUMENTS PHOTOCOPYING SERVICES', 'Siddique', None, '0544873299', 'alnisralmaassy@gmail.com', None),
	('AL NISR AL SAREE DOCUMENTS TYPING & COPYING SHARJAH', 'Abbas hussein', None, '0527844661', 'alifeg2020@gmail.com', None),
	('AL NOOR AL ASEEL TYPING AND DOCUMENTS PHOTOCOPYING SERVICES', 'Siddique', None, '0504989656', 'alaseeltoursbr1@gmail.com', None),
	('AL QALAM AL MUMAYAZ DOCUMENTS TYPING & COPYING', 'Abbas hussein', None, '0564578559', 'alqalamtypshj@gmail.com', None),
	('AL QAMAR AL SAFI Typing & Copying', 'Siddique', None, '0567656310', 'od6000@gmail.com', None),
	('AL RAAD Typing & Documents Copying', 'Siddique', None, '+971 50 368 6965', 'alraad07@gmail.com', None),
	('AL RABWA ELECTRICAL & MECHANICAL SERVICES (L.L.C)', 'Jithin Raj', None, '0545838648', 'alborjgroupshj@gmail.com', None),
	('Al Rameen Sanitary & Paints', 'caroline faru', None, '0544459704', None, None),
	('AL RAMS TYPING CENTRE', 'Siddique', None, '0551497413', 'alramstyp@gmail.com', None),
	('AL RAWAHIL TYPING & DOCUMENTS COPYING CENTER', 'Abbas hussein', None, '0551952293', 'alrawahilnp@gmail.com', None),
	('AL RAWNAQ BUSINESS MEN SERVICES', 'Siddique', None, '0507676084', 'rawnaqbms@gmail.com', None),
	('AL RIFAA DOCUMENTS TYPING & COPYING', 'Siddique', None, '0557545311', 'alrifatc@gmail.com', None),
	('AL RUAYA AL THAQIBAH TYPING AND DOCUMENTS COPYING', 'Siddique', None, '0588659522', 'alruayatyping@gmail.com', None),
	('AL SAFA DOCUMENTS TYPING & COPYING', 'Siddique', None, '0504398758', 'alsafatyping55@gmail.com', None),
	('AL SAHAM BUSINESSMEN SERVICES', 'Abbas hussein', None, '0567011200', 'sahamshj@gmail.com', None),
	('MADINAT AL SAMA AL ZARQA TYPING AND DOCUMENTS SERVICES', 'Siddique', None, '971 58 187 1733', 'Ibrukv007@gmail.com', None),
	('AL Sana Restaurant', 'Siddique', None, '00971 56 486 7018', 'thaslimdirar0007@gmail.com', None),
	('Al Saqr managment consultancy', 'Siddique', None, '507745992', 'saqrtc97@gmail.com', None),
	('Al Sayegh Documents Clearing', 'Mahmoud Nashaat', None, '0529222213', 'alsayegh777@gmail.com', None),
	('AL SEERAJ TYPING SERVICES', 'Siddique', None, '0555803365', 'alseerajtyping@gmail.com', None),
	('AL SEHR AL JANOUB TYPING CENTRE', 'Abbas hussein', None, '0553010224', 'ramyagag@yahoo.com', None),
	('AL SHAMMAS DOCUMENT TYPING & COPYING', 'Siddique', None, '0507506984', 'alshammas786@gmail.com', None),
	('AL SUHAILI TYPING CENTRE', 'Siddique', None, '565786166', 'SUHAILITYPING@GMAIL.COM', None),
	('AL TAHDEETH AL MUSTAMIR AUTO.MAINT.W.SHOP', 'Abbas hussein', None, '056300445', None, None),
	('Al Taj Smart Medical Center', 'CZG Group', None, '+971 55 608 9051', 'accounts@altajcentre.ae', None),
	('AL TAKREEM TYPING & PHOTOCOPY SERVICES', 'Siddique', None, '0556694965', 'takreemtyping@gmail.com', None),
	('AL Tareekh Documents Typing & Copying', 'Siddique', None, '+97158 5987500', 'altareekkh2020@gmail.com', None),
	('AL TASHRIFAT GULF DRESES', 'Mahmoud Nashaat', None, '0557637766', 'jaisalk1503@gmail.com', None),
	('AL TAWAR TYPING', 'Mahmoud Nashaat', None, '0552809421', 'typingaltawar@gmail.com', None),
	('AL Wadheh Document Typing & Copying Br.2', 'Siddique', None, '+971 58 224 9933', 'alwadhehbr.2@gmail.com', None),
	('AL WADYAN TYPING & DOCUMENTS COPYING', 'Siddique', None, '0501114797', 'alwadyan2023@gmail.com', None),
	('AL WAHA AL FARIDAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0565391510', 'alwahaalfaridah@gmail.com', None),
	('AL WAHA COMPUTER DEVICES TR. L L C', 'Mahmoud Nashaat', None, '+971 56 346 7780', None, None),
	('AL WATAN TYPING L.L.C.', 'Abbas hussein', None, '0552949630', 'alwatantypinguae@gmail.com', None),
	('Al Wathba Construction Company', 'Mohammad Alsmadi', None, '97100000000', None, None),
	('Al Wesal Documents Typing & Copying', 'Siddique', None, '+971 55 610 9919', 'alwesaldtc@gmail.com', None),
	('AL YASMIN BUSSINESMEN SERVICES', 'Siddique', None, '065625253', 'Shajeerybs@gmail.com', None),
	('AL ZEYARAT HOME HEALTH CARE CENTRE L.L.C.SP', 'Sabith', None, '0523011419', 'Yasameen@health2home.ae', None),
	('AL ZUJAJ AL ASFAR BLDG CLEANING', 'Mohammad Hussein Hasan', None, '0588175393', 'hireehiree977@gmail.com', None),
	('AL LULUAH AL BAYDAA TYPING AND DOCUMENTS COPYING', 'Siddique', None, '0528556282', 'shaikhmuzain@gmail.com', None),
	('AL AKEED Documents Typing & Copying', 'Siddique', None, '971523637002', None, None),
	('ALAUDDIN GEN. TR. CO. LLC.', 'Mahmoud Nashaat', None, '0508945730', 'Mohamedkhiry117@gmail.com', None),
	('ALAWEAAQ ALBANAFSAJEYAH CLEANING SERVICES', 'Mohammad Hussein Hasan', None, '0508603195', 'GADISATAMANAA@GMAIL.COM', None),
	('ALBENAA ALSHAMEL FACILITIES MANAGEMENT - SOLE PROPRIETORSHIP L.L.C.', 'Zahra', None, '971551995112', 'hr@albenaa.ae', None),
	('Albloshi PRO', 'Abbas hussein', None, '971 55 207 7714', 'Dilawarbaloch230@gmail.com', None),
	('ALBURAQ BUSINESSMEN SERVICES', 'Siddique', None, '0525942601', None, None),
	('AL DALIL MEDICAL CENTER', 'Razan Samor', None, '0581489704', 'ALDALIL.MC@GMAIL.COM', None),
	('ALDHHBYT ALALMYT FOR TENTS , SHEDS & TARPAULINS TRADING CO. L.L.C', 'Mahmoud Nashaat', None, '+971522997718', 'Mahmoud.elgohary@zhbya.com', None),
	('ALI ALJARI A/C. UNITS FIX.LLC', 'Siddique', None, '0554200770', 'SERVICE@ALIALJARIAC.COM', None),
	('alitar typing centre', 'Abbas hussein', None, '0562635192', 'alitartyping22@gmail.com', None),
	('AL ITIFAQ BLDG.CLEANING SERVICES', 'Siddique', None, '05589901', 'admin@maritechexperts.com', None),
	('Al Khuloud Typing & Doc. Copying', 'Siddique', None, '065322790', 'aktyping786@gmail.com', None),
	('Allamsa althakya typing', 'Siddique', None, '503139061', 'allamsatyping@gmail.com', None),
	('ALMAD AL AKHDHAR TYPING & DOCUMENTS COPYING', 'Siddique', None, '0502971200', 'almad.ts2022@gmail.com', None),
	('ALMAJLIS MANAGMENT COMPANY', 'Siddique', None, '065217357', None, None),
	('AL MANARAH TYPING AND COPYING SERVICES', 'Siddique', None, '0523364079', 'manarahtyping@gmail.com', None),
	('ALMARIN TYPING', 'Siddique', None, '0504994622', 'ALMARIN TYPING@GMAIL.COM', None),
	('AL MASHHOOR TYPING AND DOCUMENT COPYING', 'Siddique', None, '068852657', 'uaedoc.vat@gmail.com', None),
	('ALNOOF AUTO TYRES&ACCESSORIES', 'Mahmoud Nashaat', None, '0509865441', None, None),
	('ALQALAA ALSHAMKHAH BUILDING CLEANING SERVICES', 'Mahmoud Nashaat', None, '0564908896', 'YOUMISHAYOMI@GMAIL.COM', None),
	('Alremal contracting llc', 'Mahmoud Nashaat', None, '0552230947', None, None),
	('AL RUKN AL FETHI Businessmen Services', 'Siddique', None, '971501362021', None, None),
	('ALSHAM BUSINESS MEN SERVICES', 'Siddique', None, '0507160245', 'alsham7722@gmail.com', None),
	('ALYOUSEF OASIS PROJECT MANAGEMENT SERVICES EST.', 'Siddique', None, '0522721000', 'aliyousefoasis@gmail.com', None),
	('AL AMAN TYPING AND COPYING SERVICES', 'Siddique', None, '0547666938', 'alamantyping90@gmail.com', None),
	('AL AMANI Typing & Photocopy', 'Siddique', None, '97165255178', 'xred_love@hotmail.com', None),
	('Amazon Printing', 'Aya Mostafa', None, '0564465535', 'info@amazonpp.ae', None),
	('AMEER Documents Typing & Copying', 'Mahmoud Nashaat', None, '0567206414', 'ameertyping2019@gmail.com', None),
	('AL MARWAH TYPING AND COPYING SERVICES', 'Siddique', None, '0551271682', 'marwah@gmail.com', None),
	('AMTHAL BUSSINES CENTRE', 'Siddique', None, '0503750518', None, None),
	('Amwaj Albhr TYPING CENTRE', 'Abbas hussein', None, '0522898606', 'AMWAJALBAHR78@GMAIL.CPM', None),
	('AL NIBRAS BUSINESS MEN SERVICES', 'Siddique', None, '065664040', 'nibrasservices@gmail.com', None),
	('Amjad Nazwa contracting', 'Mahmoud Nashaat', None, '0527470813', 'amjadnazmacontracting@gmail.com', None),
	('AL ANWAR Typing', 'Siddique', None, '065670120', 'anwartyping27@gmail.com', None),
	('AOE Combo Package', None, None, '0509459167', None, None),
	('ARAB TURK INTERNATIONAL ENG. CONSULTANT CO. L.L.C', 'Siddique', None, '0505699825', 'okibrahim786@gmail.com', None),
	('Arabesk typing', 'Siddique', None, '504047995', 'arabesk.shj@gmail.com', None),
	('Arabian German LLC', 'Mahmoud Nashaat', None, '0508218450', 'arabiangermanllc@gmail.com', None),
	('AL RUKN AL SHAMIL TYPING AND DOC. CLEARANCE', 'Mahmoud Nashaat', None, '0566321442', 'alrukn999@gmail.com', None),
	('ARDH AL IBDAA PRINTING & GRAPHICS', 'Abbas hussein', None, '0562596058', 'aaigraphics@gmail.com', None),
	('ARDH AL SAADAH TYPING & DOCUM. COPYING', 'Abbas hussein', None, '97167598050', 'alsaadahtyping@gmail.com', None),
	('Areej Alebdaa Technical Services', 'Mahmoud Nashaat', None, '+971 56 903 8522', None, None),
	('Aryana Hotel LLC', 'Mahmoud Nashaat', None, '0562805706', 'pro@aryanahotels.com', None),
	('ASAAS AL THIQA TYPING & DOCUMENTS COPYING SERVICES', 'Siddique', None, '0509460678', 'asaasalthiqa@gmail.com', None),
	('AL SIRAJ AL MUNEER TRAVELS AND TYPING CENTER', 'Siddique', None, '0582752273', 'sirajmonirty2018@gmail.com', None),
	('AL ASAWAR PVT. BUSES PASSENGERS TRANSPORT LLC', 'Siddique', None, '0562881545', 'aswar.pvt.transport@gmail.com', None),
	('ASCENT TYPING', 'Siddique', None, '0551292910', 'ASCENTTYPING@GMAIL.COM', None),
	('RUKUN AL ASFAR TYPING & DOCUMENT COPYING', 'Siddique', None, '0505287224', 'rukuntc@gmail.com', None),
	('ASGC Construction LLC - Abu Dhabi/ Al Shafar Branch', 'Aya Mostafa', None, '971 506251287', None, None),
	('AL SAYARA LIMOUSINE PASSENGERS  TRANSPORT LLC SP', 'Siddique', 'Shop No.4, Al Wahda Street,  Al Majaz/Sharjah, Sharjah, 3393,  SharjahRoad), Al Soor, Sharjah, 3393, Sharjah', '+971565266046', 'hrsupport@cozmotravel.com', '100621673100003'),
	('ASMESCO FIRE FIGHTING LLC', 'Siddique', None, '0586105676', 'Pro-assistant@coremetal.net', None),
	('AL SANABIL TYPING', 'Siddique', None, '0545718868', 'alsanabildoc@gmail.com', None),
	('AL ATLAL Typing & Document Copying BR No 1', 'Siddique', None, '0555710660', 'atlalbr@yahoo.com', None),
	('AL AWAIEL BUSINESSMEN SERVICES', 'Siddique', None, '0568788891', 'alawaiel@yahoo.com', None),
	('AL AYAN TYPING & DOCUMENTS COPYING', 'Siddique', None, '0558182376', 'alayantyping@gmail.com', None),
	('BAB AL BUHAIRA Typing Services', 'Siddique', None, '0568950809', 'babalbuhaira2021@gmail.com', None),
	('BAB AL MARJAN TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '05862870780', 'babalmarjantyping@gmail.com', None),
	('BAB AL MEMZAR TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0506327871', 'babalmemzartyping@gmail.com', None),
	('BAB AL QARYA  DOCUMENTS TYPING & COPYING', 'Abbas hussein', None, '0555385154', 'babalqarya2020@gmail.com', None),
	('BAB AL QASAR Documents Typing & Copying', 'Siddique', None, '0569569234', 'babalqasardtc@gmail.com', None),
	('BAB AL ZAHIAH TYPING', 'Siddique', None, '0569644265', 'alzahiatyping@gmail.com', None),
	('BAB ALRIZ TECHNICAL SERVICES EST.', 'Siddique', None, '056 569 6162', None, None),
	('BAB KHYBER TYPING CENTER', 'Siddique', None, '0509608576', 'babkhaiber@gmial.com', None),
	('Al Badeya Typing & Documents Copying', 'Siddique', None, '0551993439', None, None),
	('BADR MUWAILEH TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0509315889', 'badrtyping786@gmail.com', None),
	('AL BADYAH BUSINESSMEN SERVICES', 'Siddique', None, '0506262635', 'albadiyah1@gmail.com', None),
	('MOHAMED ABDULRAHMAN AL BAHAR LLC', 'Razan Samor', None, '0504551730', 'Ghassan.younes@albahar.com', None),
	('Bait Al masah Aluminum & Glass Cont. LLC', 'Mahmoud Nashaat', None, '0547137545', 'baitalmasah2010@gmail.com', None),
	('BAIT AL MUHEET TYPING & DOCUMENT COPYING', 'Siddique', None, '0561188667', 'baitalmuheettyping@gmail.com', None),
	('BAB AL ROLLA TYPING & DOCUMENTS COPYING', 'Siddique', None, '0558328678', 'babalrolahtyping@gmail.com', None),
	('AL BARAKA DOCUMENTS TYPING', 'Siddique', None, '0552852196', 'BARAKATYPING@GMAIL.COM', None),
	('BARCELONA BUSINESSMEN SERVCES', 'Siddique', None, '0563957776', 'barcelonabusinessmen@gmil.com', None),
	('BARCODE ELECTROMECHANICAL WORKS', 'Mahmoud Nashaat', None, '0543927708', None, None),
	('BAB AL RAYAN DOCUMENTS TYPING AND COPYING', 'Siddique', None, '0557458481', 'babalrayantyping@gmail.com', None),
	('Bareeq project managment', 'Mahmoud Nashaat', None, '0505595167', 'bareeqprojectmanagement@gmail.com', None),
	('BASIL BADR PRO.', 'Mahmoud Harara', None, '0509740989', None, None),
	('BASMAT AL NABAAH DOCUMENTS TYPING & COPYING', 'Siddique', None, '0508637652', 'bantyping11@gmail.com', None),
	('BAWABAT AL WAHDA Typing & Document Copying', 'Siddique', None, '0565263281', 'Alwahdatyping2@gmail.com', None),
	('BAWABAT AL YARMOOK TYPING & DOCUM.COPYING', 'Siddique', None, '0553082421', 'baytypingcenter@gmail.com', None),
	('BAWABAT ROWAD BUSINESS MEN SERVICES', 'Siddique', None, '0522290397', 'bawabatrowad@gmail.com', None),
	('BERG Industeries LLC', 'Siddique', None, '97172211558', 'pro@bergengg.com', None),
	('Best Trip Tourism', 'Abbas hussein', None, '0529230356', 'acc.besttriptourism@gmail.com', None),
	('Bhamra Pools Technical Services LLC', 'Siddique', None, '0559430401', 'bhamrapools@gmail.com', None),
	('AL BIDAYA Management Cosultancy', 'Siddique', None, '065638727', 'albidaya@gmail.com', None),
	('Business Incorporation Zone FZ LLC', 'CZG Group', 'Dubai Branch 13 & 14,The Iridium Building Umm Suqeim Road, Al Barsha, P.O.Box 391186, Dubai, U.A.E Dubai', '055 241 0226', 'accounts@bizincorp.ae', None),
	('BLACK LINE Typing & Document Copying', 'Siddique', None, '065674066', 'blacklineblt@gmail.com', None),
	('Blue Flame Fire fighting llc', 'Siddique', None, '0528078039', 'blueflame@gmail.com', None),
	('BOSALIM Documents Typing & Copying', 'Siddique', None, '0581328233', 'bosalim714@gmail.com', None),
	('Typing Bro', 'Siddique', None, '0555182750', 'typingbrofirst@gmail.com', None),
	('btc typing centre', 'Abbas hussein', None, '0542262960', 'fasalurahmanb2c@gmail.com', None),
	('BURJ AL RAYHAN TYPING & DOCUMENTS COPYING', 'Siddique', None, '0524659944', 'alrayhantyping@gmail.com', None),
	('BAB AL BUTHINA Typing and Copying', 'Mahmoud Nashaat', None, '0552802288', 'butheenatyping@gmail.com', None),
	('Cad Contracting Company', 'Aya Mostafa', None, '971 504337702', None, None),
	('Captains Freight', 'CZG Group', None, '971 50 5006634', 'pro@captainsfreight.com', None),
	('Care Tech', 'Mahmoud Nashaat', None, '0555995235', None, None),
	('Carrefour', 'Mahmoud Nashaat', None, '0507192004', None, None),
	('Central Hospital Sharjah', 'Siddique', None, '0523366132', 'sajanboosi@yahoo.com', None),
	('Chowking Restaurant', 'Mahmoud Nashaat', None, '0567274718', None, None),
	('hazem khalil', 'hazem khalil', None, '0509459167', None, None),
	('Coca-Cola', 'Aya Mostafa', None, 'abdulharif@coca-cola.co.ae', '0558986008', None),
	('COOL LINE RAD.& AUTO,SPARE PARTS TR.LLC', 'Siddique', None, '0508182678', 'hr@coolline-group.com', None),
	('CORE METAL INDUSTRY L.L.C', 'Siddique', None, '0586105676', 'Pro-assistant@coremetal.net', '104629601600003'),
	('CORNICHE HOTEL SHARJAH', 'Mahmoud Nashaat', None, '050 106 6581', 'chornichehotelsharjah@gmail.com', None),
	('COSMOPLAST INDUSTRIAL CO LLC', 'Siddique', None, '0504620195', 'fawziya.gharib@cosmoplast.com', None),
	('CSP club ,Unity partners', 'Aya Mostafa', None, '+971 50 881 0610', None, None),
	('COZMO TRAVEL L L C - SOLE PROPRIETORSHIP', 'Siddique', None, '+971 56 526 6045', 'hrsupport@cozmotravel.com', '100019554300003'),
	('cyber space', 'caroline faru', None, '0556577332', None, None),
	('CYLINGAS Engineering & Construction', 'Siddique', None, '0586585934', 'aadam@cylingas.ae', None),
	('CYLINGAS  EMBASSY', 'Aya Mostafa', None, '0586585934', 'aadam@cylingas.ae', None),
	('CREATIVE ZONE FZ LLC', 'CZG Group', 'Suite 1702, Level 17, Boulevard Plaza Tower 1 Sheikh Mohammed Bin Rashid Boulevard,  Downtown Dubai,  P.O.Box 27363, Dubai, UAE', '0564089262', 'payables@creativezone.ae', '100230758300003'),
	('DAR AL JAMHOUR BUSINESSMEN SERVICES', 'Siddique', None, '0526309056', 'infotyping52@gmail.com', None),
	('AL DALEEL TYPING CENTRE', 'Siddique', None, '0502147061', 'dtmr2020@gmail.com', None),
	('Dar Al Maha Documents Typing & Copying', 'Siddique', None, '97165669918', 'daralmahatyping@gmail.com', None),
	('DAR AL NIBRAS Typing & Document Copying', 'Siddique', None, '0505162716', 'daralnebrasuae@gmail.com', None),
	('DAR AL KHAIR TYPING & DOCUMENTS COPYING', 'Siddique', None, '065460666', 'daraalkahir333@gmail.com', None),
	('DAR AL ESLAH Typing & Documents Copying', 'Siddique', None, '0503178449', 'daraleslah1@gmail.com', None),
	('DAR AL FALAH DOCUMENTS TYPING& COPYING', 'Siddique', None, '0509489225', 'daralfalahtyping@gmail.com', None),
	('DAR AL FAYHA GROUP OF COMPANIES', 'Siddique', None, '050 4773675', 'daralfayhauae@gmail.com', None),
	('DAR AL IETEMAD MEAT TR LLC', 'Siddique', None, '971 50 229 7204', 'hr1@aleatemad.ae', None),
	('DAR AL IETEMAD REST. L.L.C', 'Siddique', None, '+971 50 229 7204', 'hr1@aleatemad.ae', None),
	('DAR AL KARAMAH TRADING CENTER', 'Siddique', None, '0557127949', 'daralkaramahtr@gmail.com', None),
	('DAR AL MAHATTA DOCUMENTS TYPING', 'Siddique', None, '0528008323', 'daralmahattatyping@gmail.com', None),
	('DAR AL MURJAN TYPING & DOCUMENTS COPYING', 'Siddique', None, '0585870589', 'dar.al.murjan.typing@gmail.com', None),
	('DAR AL NOOR TYPING & DOCUMENTS COPYING', 'Siddique', None, '0551554408', 'daralnoortyp@gmail.com', None),
	('DAR AL SEROOR TYPING', 'Abbas hussein', None, '0569639128', 'daralseroortyping@gmail.com', None),
	('DAR AL TAMAYEZ DOCUMENTS TYPING', 'Abbas hussein', None, '053348831', 'tamayeztyping@gmail.com', None),
	('DAR AL WAHA TYPING & DOCUMENTS COPYING', 'Siddique', None, '505426207', 'daralwaha22@gmail.com', None),
	('DAR AL YASH TYPING SERVICES', 'Abbas hussein', None, '0525064414', 'alyashtypingbr1@gmail.com', None),
	('Dar Alsaadah', 'Razan Samor', None, '0545573411', 'Daralsaadah18@gmail.com', None),
	('Dar alshafaa technical service', 'Mahmoud Nashaat', None, '0505595167', 'alshafatechnicalservice@gmail.com', None),
	('DAR AL AMAN Documents Typing & Copying', 'Siddique', None, '065316444', 'daralaman444@gmail.com', None),
	('Al darahim management consultants & stamp works L.L.C', 'Mahmoud Nashaat', None, '0501555602', 'dubai22@hotmail.com', None),
	('DATA VISION USED DEVICES TRADING L L C', 'Mahmoud Nashaat', None, '971 56 346 7780', None, None),
	('AL DAW AL SAREE Typing & Docum. Copying', 'Siddique', None, '065300037', 'aldawalsaree@gmail.com', None),
	('DAR  ELETMAD  MEAT TR', 'Noha', None, '0502297204', 'etimad.meat@gmail.com', None),
	('DENIBA INTERNATIONAL EXCHANGE', 'Jithin Raj', None, '050 405 7033', 'denibaexchange@gmail.com', None),
	('AL DHAW AL AKHDHAR Typing & Documents Copying', 'Siddique', None, '0555248894', 'ashrafali2174@gmail.com', None),
	('DINAR TYPING', 'Siddique', None, '0503034364', 'dinartyping@yahoo.ccom', None),
	('Direct Documents Clearing Services LLC', 'Abbas hussein', None, '0549915805', 'directaweer@gmail.com', None),
	('AL DOLPHIN AL AZRAQ', 'Siddique', None, '065732726', 'dolphintyping2016@gmail.com', None),
	('DUNIA AL IBDAA TYPING & DOCUMENTS COPYING', 'Siddique', None, '0509558384', 'duniashjuae@gmail.com', None),
	('AL DURAH FOUNDATIONS', 'Mahmoud Nashaat', None, '0503609182', 'masoom1972@gmail.com (Durah)', None),
	('DUWAR AL YARMOUK DOCUMENTS TYPING & COPYING', 'Siddique', None, '0503406398', 'duwaralyarmouktyping@gmail.com', None),
	('DXB Combo Package', None, None, '0509459167', None, None),
	('Dynatrade - Al Shahid', 'Siddique', None, '0509955429', 'dynatrade@gmail.com', None),
	('EASY HANDS TYPING & DOCUMENTS COPYING LLC SP', 'Siddique', None, '0564728905', 'contact@easyhands.ae', None),
	('EASY WAY DOCUMENTS TYPING', 'Siddique', None, '0503582100', 'easywaydocum@gmail.com', None),
	('EFADA DOCUMENTS CLEARING SERVICESS LLC', 'Abbas hussein', None, '0528510477', 'efada.cr@gmail.com', None),
	('Emirates Fast Food Company LLC', 'Aiban', None, '0564018326', 'reymond.tabora@mcdonalds-uae.com', None),
	('AL EJRAA AL SAAREE', 'Siddique', None, '0507171372', 'amr.gbr700@gmail.com', None),
	('Elister Technologies LLC', 'Sabith', None, '0526921406', 'Mkunnil@elister-me.com', None),
	('ELITE ZONE DELIVERY SERVICES - SHJ. BR', 'Jithin Raj', None, '971 52 113 1153', 'pro@zoneeliteinv.com', None),
	('ELSAYED ISSA & EMAM TECHNICAL SERVICES L.L.C', 'Mahmoud Nashaat', None, '0509081226', 'me9295858@gmail.com', None),
	('EMERALD CORNER TYPING AND DOCUMENTS PHOTOCOPYING SERVICES L.L.C.', 'Abbas hussein', None, '0553292786', 'emeraldtyping@yahoo.com', None),
	('AL ENWAN Typing & Copying Services', 'Siddique', None, '0526186598', 'alenwantyping@gmail.com', None),
	('Faisal Holding  L.L.C.SP', 'Mahmoud Nashaat', None, '+971 56 700 0671', 'a.elghazally@faisalholding.com', None),
	('FAJAR AL FALAH DOCUMENTS TYPING & COPYING', 'Abbas hussein', None, '0552324906', 'fajaralfalahtypingcenter@gmail.com', None),
	('AL FAJR Document Typing & Copying', 'Siddique', None, '065660087', 'alfajr100@gmail.com', None),
	('ABDULLAH AL FALASY Document Typing', 'Siddique', None, '0501017491', 'alfalasytyping@gmail.com', None),
	('FALCON VISION Documents Typing', 'Siddique', None, '065462700', None, None),
	('FAN AL ITQAN DOCUMENTS TYPING AND COPYING', 'Siddique', None, '0508430295', 'fanalitqantyping@gmail.com', None),
	('AL FARIS Typing & Document Copying', 'Siddique', None, '065552077', 'faristyping@gmail.ccom', None),
	('FARIS AL BAHR TYPING & DOCUMENTS COPYING', 'Siddique', None, '0563532451', 'farisalbahrtyping@gmail.com', None),
	('Faris Al madinah typing center', 'Siddique', None, '065737485', 'Faristc@gmail.com', None),
	('AL FARWANIAH TECHNICAL SERVICES', 'Siddique', None, '0524220017', 'Alfarwaniah.ae@gmail.com', None),
	('FAST FOCUS TYPING & DOCUMENTS COPYING', 'Siddique', None, '0508289152', 'fastfocusuae.ae@gmail.com', None),
	('FAST LINKS BUSINESS CONSULTANCY', 'Siddique', None, '0509933701', 'fastlinksbusiness@gmail.com', None),
	('FAST POINT TYPING & Documents Clearing', 'Siddique', None, '0501250382', 'typingfastpoint@gmail.com', None),
	('FAST SOLUTIONS SERVICES', 'Siddique', None, '0507831041', 'info@fast-solutions.ae', None),
	('FAST LINE TYPING AND DOC. SERVICES', 'Siddique', None, '0509492091', 'info@fastlinetyping.com', None),
	('FAZAH TYPING & DOCUMENT COPYING', 'Siddique', None, '0569692757', 'fazahtyping1@gmail.com', None),
	('AL FAYDAH BUSINESSMEN SERVICES', 'Mahmoud Nashaat', None, '0542865051', 'alfaydahbusiness@gmail.com', None),
	('FIRST CLASS MANAGEMENT CONSULTANCY', 'Siddique', None, '0543751787', 'fmc.typing@gmail.com', None),
	('Finacc accounting', 'Abbas hussein', None, '0522374540', 'businessfinacc@gmail.com', None),
	('FIRST CONSULTANT BLDG.MAT.TR. L.L.C', 'Razan Samor', None, '0529554004', 'Admin-assistant@dr-scent.com', None),
	('FIRST FLEET LINE DELIVERY SERVICES L.L.C', 'Abbas hussein', None, '0508879748', 'hr@bikeboxmt.com', None),
	('FOCUS Documents Typing & Copying Services', 'Siddique', None, '0503546753', 'focustypinguae.ae@gmal.com', None),
	('AL FOUZ TYPING CENTER', 'Siddique', None, '065663318', None, None),
	('Funoon DOCUMENTS CLEARING SERVICES', 'Abbas hussein', None, '0581981237', 'funoonbr@gmail.com', None),
	('GALA SUPERMARKET DMCC', 'Abbas hussein', None, '971566865517', 'hr.manager@galaorg.com', None),
	('GENTLE PARK READYMADE GARMENTS LLC', 'AL TAJ', None, '0554260047', 'mohdosmanbd@gamil.com', None),
	('Al Ghazal Typing & Docum. Copying', 'Siddique', None, '971 50 757 6232', 'ghazaltyping@gmail.com', None),
	('AL GHUBAIBA Typing & Photocopying', 'Siddique', None, '0526287330', 'ghubaibat@gmail.com', None),
	('GIFFIN GRAPHICS COMPANY - W L L - SHJ.BR', 'Rasheed', None, '0555222435', 'M.DAYAT@GIFFINGRAPHICS.COM', None),
	('GIFT MARKET', 'Mahmoud Nashaat', None, '0504994176', None, None),
	('GLOBAL LINKS MANAGEMENT CONSULTANCY', 'Siddique', None, '0581010786', 'uaeglobal9@gmail.com', None),
	('GLOBAL STUDIES UNIVERSITY', 'Mahmoud Nashaat', None, '065112444', 'hr@theafricainstitute.org', None),
	('GLORY GRAPHICS DUBAI  UAE', 'Siddique', None, '0503830327', 'GLORYGRAPHICS12@GMAIL.COM', None),
	('GOLDEN IMAGE TYPING CENTER', 'Siddique', None, '0501876720', 'docscenteruae2@gmail.com', None),
	('GOOD DAY Typing Documents & Copying', 'Siddique', None, '971505105722', 'gdtdc2021@gmail.com', None),
	('Good Luck Documents Typing & Copying', 'Siddique', None, '97165466810', 'goodluckdtc@gmail.com', None),
	('Granada roastery', 'Mohammad Hussein Hasan', None, '0553588799', None, None),
	('GREEN SIGNAL PERFUMES TRADING L.L.C', 'Razan Samor', None, '0529554004', 'Admin-assistant@dr-scent.com', None),
	('Group for Securicor for General Services', 'Aya Mostafa', None, '971 554470251', None, None),
	('Gulf Asia Contracting', 'Mahmoud Nashaat', None, '0529095605', 'hrd8@rpgroupco.ae', None),
	('HABAT AL LULU TYPING AND DOCUM', 'Siddique', None, '0555997270', None, None),
	('Habeeba Passengers Transport by Rented Buses llc', 'Mohammad Hussein Hasan', None, '0508463273', None, None),
	('AL HAFOUF TYPING AND DOC. COPYING', 'Siddique', None, '0565919993', 'alhafouftyping@gmail.com', None),
	('HASAN AL HAMMADI Public Related Services', 'Siddique', None, '971543095303', 'info@hammadiuae.com', None),
	('AL Hasanat Typing', 'Siddique', None, '+971 6 5732 449', 'hasanattyping@gmail.com', None),
	('HASSAN ABO GHALEB LLC', 'Aya Mostafa', None, '0556941694', None, None),
	('HATTA AUTO.REP.W.SHOP', 'Mahmoud Nashaat', None, '0529125393', 'PRO@KMGROUP.AE', None),
	('BAB AL HAYAT TYPING AND DOC. COPYING', 'Siddique', None, '0506605546', 'hayathguest@gmail.com', None),
	('HEALTH INSURANCE', 'CZG Group', None, '0565064765', 'accounts@altajcentre.ae', None),
	('HIPSTER CORPORATE SERVICES PROVIDER', 'Abbas hussein', None, '0552555064', 'Danishkmt@gmail.com', None),
	('HASHIM MOOSA Documents Typing & Copying', 'Siddique', None, '0503739371', 'hmholidays2020@gmail.com', None),
	('HORIZON SURVEY COMPANY FZE Sharjah.', 'Siddique', None, '056507171285', 'muhammad.musthafa@horizon-geosciences.co', None),
	('HIGHT SKY project management service.', 'Mahmoud Nashaat', None, '0552698884', 'Eng.ahmedzubair202@gmail.com', None),
	('AL HULM DOCUMENT TYPING', 'Siddique', None, '0508627571', 'alhulm2012@gmail.com', None),
	('HUMMING BIRD USED DEVICES TRADING LL C', 'Mahmoud Nashaat', None, '+971 56 346 7780', None, None),
	('IBDAA OMRAANI TECHNICAL', 'MOHAMMED OTSMAN', None, '0504085968', 'Gabersoliman93@gmail.com', None),
	('ICell Telecom', 'Noha', None, '0565399681', 'mamoonaz@yahoo.com', None),
	('AL IHRAM Typing & Document Copying', 'Siddique', None, '0502789099', 'alahramtyping@gmail.com', None),
	('TAREEQ AL IHSAN TYPING SERVICES', 'Siddique', None, '0567141288', 'tareeqalihsantyping@gamil.com', None),
	('IMPRATOR ALKARAM CAFE', 'MOHAMED ABDELRAHMAN', None, '0505508051', None, None),
	('INJAZ MUAMALATY DOCUMENTS CLEARING SERVICES', 'Siddique', None, '0509146146', 'sales@muamalaty.com', None),
	('Inter Mass Engineering & Contracting L.L.C', 'Mahmoud Nashaat', None, '050 4628146', 'hareendran.pillai@intermass.ae', None),
	('IQRAH typing center', 'Siddique', None, '+971 50 737 8263', 'IQRAHTYPINGCENTER@GMAIL.COM', None),
	('AL ISKANDRIAH Typing & Document Copying', 'Siddique', None, '0526880078', 'alexandria_typing@yahoo.com', None),
	('ISRA MANAGEMENT TYPING', 'Siddique', None, '0504271285', 'khattakjee101@gmail.com', None),
	('AL ITEFAQ BUSINESSMEN SERVICES', 'Siddique', None, '065668963', 'alithifaq786@gmail.com', None),
	('AL ITQAN AL MUTAMAYEZ TYPING & DOCUMENTS COPYING', 'Siddique', None, '0552979240', 'alitqan2016@yahoo.com', None),
	('JAMAL ABDULLA', 'Siddique', None, '0501394512', 'akthaj@gmail.com', None),
	('JABAL AL ABEER TECHNICAL SERVICES EST', 'Siddique', None, '0564703574', 'kumaran.srm09@gmail.com', None),
	('AL JABAL AL AHMAR TYPING AND DOCUMETS COPYING', 'Siddique', None, '0529449432', 'ajaatdc@gmail.com', None),
	('JABAL AL MANAMA TYPING & DOCUMENTS PHOTOCOPYING SERVICES', 'Abbas hussein', None, '0547103966', 'jmtyping2024@gmail.com', None),
	('JAMAL ABDULLA DOCUMENTS CLEARING SERVICES', 'Siddique', None, '0558366939', 'info@thebusinesssetup,com', None),
	('AL JANOUB Documents Typing & Copying', 'Mahmoud Nashaat', None, '0551723544', 'aljanoubdtc@gmail.com', None),
	('JAR AL QAMAR SANITARY CONT.', 'Siddique', None, '0561847873', 'SABBANI.SREENIVAS123@GMAIL.COM', None),
	('AL JARF Typing & Documents Copying', 'Siddique', None, '0502433190', 'aljarf.typing@gmail.com', None),
	('JAVA Typing Documents Copying', 'Siddique', None, '065746466', 'javatyping@gmail.com', None),
	('AL JAWAB Typing Documents & Businessmen Services', 'Siddique', None, '0559601881', 'aljawab14@gmail.com', None),
	('JUST DIGITAL BUSINESS SOLUTIONS FZE', 'Aya Mostafa', None, '0562406709', 'INFO@JDBUSINESS.AE', None),
	('JESRAL MADEENA', 'Siddique', None, '503078115', 'jesralmadeena@gmail.com', None),
	('JSIR MUWAILEH Typing', 'Siddique', None, '065393881', None, None),
	('JWHRT ALHR FOR MARKETING MANAGEMENT EST.', 'Mahmoud Nashaat', None, '+971 56 930 0343', '0569300343@gmail.com', None),
	('KHATIB & ALAMI CONTRACTING', 'Mahmoud Nashaat', None, '0557281758', 'khatibalamicontracting@gmail.com', None),
	('KALTON TRANSPORT L.L.C', 'Siddique', None, '0586105676', 'Pro-assistant@coremetal.net', '104995356300003'),
	('KHAT AL NAJAH Typing & Documents Copying', 'Siddique', None, '0547761836', 'khatalnajahtyping@gmail.com', None),
	('AL KANZ Business Solutions', 'Siddique', None, '0503622866', 'alkantyping@gmail.com', None),
	('AL KARAM Business Men Sevices', 'Siddique', None, '0557783852', 'alkaramb2020@gmail.com', None),
	('KAT ARABIA GENERAL CONTRACTING - L.L.C', 'Aiban', None, '0521983499', 'hr@katgroup.ae', None),
	('AL KAYAN Typing & Documents Copying', 'Siddique', None, '0545481586', 'alkayantyping@gmail.com', None),
	('KHADAMAT AL NUKHBAH TYPING & DOCUMENTS PHOTOCOPYING SERVICES', 'Abbas hussein', None, '0566676567', 'khadamatalnukhba@gmail.com', None),
	('Khadmaty Al Mumyza Businessmen Services.', 'Siddique', None, '0559866712', 'amaninet786@gmail.com', None),
	('DAR AL KHAIMA GARMENTS TRADING LLC', 'Siddique', None, '0502348093', 'DARALKHAIMA99@GMAIL.COM', None),
	('AL KHAIR TYPING AND LEGAL CONSULTANCY', 'Siddique', None, '0501252772', 'info@alkhairtyping.com', None),
	('Khaled Farouq Plaster & Tiles Con', 'Noha', None, '0507879983', 'khaledfarouqplaster@gmail.com', None),
	('AL KHALEDIYA Typing & Document Copying', 'Siddique', None, '0551206088', 'khalediyatyping@gmail.com', None),
	('AL KHARAZ Typing', 'Siddique', None, '0653661155', None, None),
	('AL KHAT AL RAFIEE Typing & Copying', 'Siddique', None, '0504550488', 'alkhat021@gmail.com', None),
	('Khat Al Aman TYPING & DOCUMENTS COPYING LLC', 'Siddique', None, '+971 50 308 8945', 'typingalaman@gmail.com', None),
	('KHOBRAA ALINJAAZ Typing & PRO Services', 'Siddique', None, '0506313255', 'injaazdxb@gmail.com', None),
	('KUWAIT NETWORK ELECTRONIC TECHNOLOGY LLC', 'Razan Samor', None, '0501172320', 'Mystro111bargas@yahoo.com', None),
	('LARSEN & TOUBRO LIMITED ECC CONSTRUCTION GROUP(SHJ.BR.)', 'Abbas hussein', None, '0508879748', 'ALI-OSMAN@LNTECC', None),
	('LIFETIME DOCUMENTS CLEARING & TYPING LLC', 'Siddique', None, '0505798590', 'lifetimetyping@gmail.com', None),
	('LINCOLN University', 'ASHIF', None, '0526463455', 'bibin@lubm.education', None),
	('LOLAT AL BAHAR DOCUMENTS TYPING & COPYING', 'Siddique', None, '0565263280', 'lolattyping@gmaIl.com', None),
	('LOUTFY ADEL FOR BUSINESS SOLUTIONS', 'Aiban', None, '0502223063', 'info@loutfyadel4bs.pro', None),
	('CUSTOMER LOYALTY PROGRAM', 'CZG Group', None, '0565064765', 'accounts@altajcentre.ae', None),
	('LEADERS WAY Document Typing & Copying', 'Siddique', None, '0557200273', None, None),
	('AL MAANY Documents Typing & Copying', 'Siddique', None, '065437066', 'almaanytyping@gmail.com', None),
	('MADO DONDURMA CORPORATE AND INSTITUTIONAL MANAGEMENT SERVICES L.L.C', 'Aya Mostafa', None, '0568614858', 'info@mado.ae', '104845166800003'),
	('AL MAHATTA Typing & Document Copying', 'Siddique', None, '065506966', 'almahatta07@gmail.com', None),
	('Mahmoud Nashaat Personal Customer', 'Mahmoud Nashaat', None, '0504370153', None, None),
	('Mahmoud Harara Personal Customer', 'Mahmoud Harara', None, '0508798066', None, None),
	('AL MAIDAN Typing & Documents Copying', 'Siddique', None, '0503841070', 'Irfad007@hotmail.com', None),
	('NOOR AL MAJAZ TYPING', 'Mahmoud Nashaat', None, '0552353893', 'majaztyp@gmail.com', None),
	('Majestic group LLC', 'Mahmoud Nashaat', None, '0507982218', 'Mujahed@majestichotels.com', None),
	('MAKKAH Typing & Document Copying', 'Siddique', None, '0527955186', 'makkahtyping@gmail.com', None),
	('MALABAR Business Man Services', 'Siddique', None, '0544855755', 'malabarbusiness@gmail.com', None),
	('MALABAR GROUP', 'Johnson Peter', None, '052 722 2916', 'malabargroup@gmail.com', None),
	('AL MANAR METAL DOORS & WINDOWS IND. CO. SOLE PROPRITORSHIP', 'Razan Samor', None, '0506960723', 'eslamzakaria.ez91@gmail.com', None),
	('MANARAT ALFAJR  TYPING AND DOCUMENTS SERVICES', 'Siddique', None, '0508042525', 'sayeedgroup333@gmail.com', None),
	('AL MANDHAR BUSINESSMEN SERVICES', 'Mahmoud Nashaat', None, '0581867865', 'almandhartyping@gmail.com', None),
	('AL MARAYA Typing Center', 'Siddique', None, '0566653939', 'almarayatyping@yahoo.com', None),
	('Al Marfa Documents Typing & Copying', 'Siddique', 'King Abdul Aziz Street, Behind Mega Mall, Sharjah', '+971 55 808 2435', 'almarfa786@gmail.com', None),
	('MAROOF PRO {TASHEEL BUTINA SHARJAH}', 'Siddique', None, '0565541533', 'maroofshj@gmail.com', None),
	('Al Marwan General Contracting', 'Dina Ablan', 'Lead source : Dina Ablan', '0508480002', None, None),
	('MASAR AL AMANA TYPING & DOCUMENTS SERVICES', 'Siddique', None, '0507097443', 'info@masalamana.ae', None),
	('Mazeed LLC', 'CZG Group', None, '0526402776', 'omair@smsemail.co', None),
	('MUHAMMAD BIN LADEN', 'Mahmoud Nashaat', None, '0502549195', 'luai.saleh@diyardev.com', None),
	('MEDCARE HOSPITAL', 'Siddique', None, '0559008413', 'GR@MEDCAREHOSPITAL.COM', None),
	('AL MEFTAH AL THAHABI Typing & Documents Copying', 'Mahmoud Nashaat', None, '0556518952', 'mdmorshed89@gmail.com', None),
	('METITO CHEMICAL', 'Siddique', None, '050 1297867', 'ASIK-MOHIDEEN@METITO.COM', None),
	('EQUUS MANAGEMENT SERVICES L.L.C - FZ - Meydan', 'CZG Group', 'The Meydan Hotel, Meydan Road, Nad Al Sheba, Dubai', '052 504 3483', 'vivek@meydanfz.ae', None),
	('MOHAMMED GHOUS Documents Typing & Copying', 'Siddique', None, '0503600852', 'mgb.typ@gmail.com', None),
	('Muhammed Hussain - Personal Customers', 'Mohammad Hussein Hasan', None, '0504649458', None, None),
	('AL MIARAJ TYPING AND DOCUMENTS COPYING', 'Siddique', None, '0552309094', 'miarajtyping@gmail.com', None),
	('Milano Touch', 'caroline faru', None, '0544459704', None, None),
	('MILLION GATE FOR BUSINESS SERVICES', 'Abbas hussein', None, '0567738751', 'milliongatetyping@gmail.com', None),
	('MIMAR EMIRATES ENGINEERING CONS /L.L.C - AJMAN', 'Mohammad Hussein Hasan', None, '97156 686 7068', 'diana.nisreeni@mimar-group.com', None),
	('M E A MIMAR ENGINEERING CONSULTANTS - DUBAI', 'Mohammad Hussein Hasan', None, '97156 686 7068', 'diana.nisreeni@mimar-group.com', None),
	('MIMAR EMIRATES ENG. CONSULTANTS - SHARJAH', 'Mohammad Hussein Hasan', None, '971 6 5549922', 'diana.nisreeni@mimar-group.com', None),
	('Misbah Al Amal Typing & Documents Copying', 'Siddique', None, '0524710172', 'mbctyping@gmail.com', None),
	('Al misk properties\xa0& Alf Tech.cont', 'AL TAJ', None, '0565480089', 'pro.nadeem@miskprops.com', None),
	('MUHAMMAD KASHIF DOCUMENTS COPYING & TYPING', 'Mahmoud Nashaat', None, '0504064185', 'mkashiftdc@gmail.com', None),
	('MOHAMED ABDELKAWI PRO', 'Siddique', None, '0529270068', 'MAN1922@YAHOO.COM', None),
	('Mohamed Shan pro', 'Abbas hussein', None, '971 54 569 9213', 'Highlandbusiness4@gmail.com', None),
	('MOHAMMED SHANU PRO (BARQA GROUP)', 'Siddique', None, '0562016708', 'MD.SHANUK@GMAIL.COM', None),
	('MONILEK OIL FILED  ENTERPRISE', 'ASHIF', None, '0555660548', None, None),
	('AL MOUMIN TYPING & DOCUMENT COPYING', 'Mahmoud Nashaat', None, '0522825055', 'almoumin2016@gmail.com', None),
	('MR PRO DOCUMENTS CLEARING', 'Siddique', None, '0552430124', 'misterproservices@gmail.com', None),
	('MAGIC TRADING COMPANY', 'Siddique', None, '0551022302', None, None),
	('MARHABA TYPING AND DOCUMENTS COPYING', 'Siddique', None, '97165792013', 'Marhabasharjah@gmail.com', None),
	('AL MUFEED TYPING & Documents Copying', 'Siddique', None, '065739747', 'mufeed2007@gmail.com', None),
	('MUFTAH AL TAWASOL TYPING & COPYING DOCUMENT', 'Siddique', None, '0545880318', 'altawasolt@gmail.com', None),
	('MUHAMMED KHALID PRO', 'Siddique', None, '0582396066', 'UNAISTABA@GMAIL.COM', None),
	('MUKHASHAB Typing & Document Copying', 'Siddique', None, '0505694163', 'mtdc1992@gmail.com', None),
	('WAHAT AL MUKHLIS TYPING & DOCUM. COPYING', 'Siddique', None, '0553171407', 'almukhlis12@gmail.com', None),
	('AL MUNA TYPING SERVICES', 'Siddique', None, '0501848415', None, None),
	('Muneer - PRO Services', 'Siddique', None, '0559866712', 'amaninet786@gmail.com', None),
	('AL MUNTAHA Typing Centre', 'Siddique', None, '0582349050', 'almuntaha821@gmail.com', None),
	('MURAD MIAH TYPING', 'Mahmoud Nashaat', None, '0504411839', 'muradmiahtyping@gmail.com', None),
	('MUSAFIR TYPING SERVICES', 'Siddique', None, '0581473983', 'musafirtyping@gmail.com', None),
	('AL MUSHAN TYPING', 'Siddique', None, '0569272783', 'abdhulrazaquecp1986@gmail.com', None),
	('MUSTAFA HASHMI - SHAMS', 'CZG Group', None, '+971 55 403 3010', 'mustafa.hashmi@shamsfz.ae', None),
	('MUTABAA BUSINESSMEN SERVICE CENTRE', 'Siddique', None, '0502217762', 'hamed.mutabaa@gmail.com', None),
	('Nad Wasit Typing & Copying Services', 'Siddique', None, '0547185237', 'nadwasittyping@gmail.com', None),
	('NADA CONTRACT CLEANING CO.LLC', 'Abbas hussein', None, '971566468386', 'riad@nadaco.ae', None),
	('NAJMAT AL FALAH Typing & Photo Copying Br-2', 'Mahmoud Nashaat', None, '0558402442', 'najmatalfalah@gmail.com', None),
	('Naffco sharjah branch', 'Mahmoud Nashaat', None, '054559844', 'm.younes@naffco.com', None),
	('AL NAHDAH Typing & Document Copying', 'Siddique', None, '0506776435', 'alnahdah2008@gmail.com', None),
	('AL NAJAH TYPING & COPYING', 'Siddique', None, '0554414492', 'alnajah019@gmail.com', None),
	('NAJAMAT AL FALLAH TYPING & PHOTOCOPYING', 'Siddique', None, '0553816444', 'najamatalfallah@gmail.com', None),
	('Najm alrabei technical services', 'Mahmoud Nashaat', None, '050559516', None, None),
	('NAJMAT AL NOOR Typing & Copying Office', 'Siddique', None, '0558181705', 'alnoordcs@gmail.com', None),
	('NAJMAT AL FAJER TECHNICAL SERVICES', 'Siddique', None, '0558525566', None, None),
	('Najran Graphics TYPING CENTER', 'Siddique', None, '0521488077', 'najrantyping@gmail.gmail.com', None),
	('NAJIM AL MADINAH Documents Typing & Copying', 'Mahmoud Nashaat', None, '0552335356', 'najimalmadinah@gmail.com', None),
	('AL NAMAT Typing & Photo Copying', 'Siddique', None, '0556313817', 'alnamattyping@gmail.com', None),
	('NAJMAT AL NAHDAH Documents Typing & Copying', 'Mahmoud Nashaat', None, '0554827250', 'najmatalnahdah@gmail,com', None),
	('NOOR AL QASIMIAH DOCUMENTS & COPYING', 'Siddique', None, '0523899406', 'typing.naq@gmail.com', None),
	('NASAR PRO', 'Siddique', None, '0581868757', 'ABDULNAZER04329@GMAIL.COM', None),
	('Nasco Mobile & Accessories', 'Noha', None, '0552636464', None, None),
	('AL NASEEB DOCUMENTS TYPING COPYING', 'Mahmoud Nashaat', None, '0527198471', 'alnaseeb786@gmail.com', None),
	('NASEER AHMED TYPING & MANAGEMENT CONSULTANT', 'Siddique', None, '0501252414', 'naseer.typing2009@gmail.com', None),
	('AL NASIR Typing', 'Siddique', None, '0567045260', 'alnasirtyping@gmail.com', None),
	('National Plastic & building material industries LLC', 'Abbas hussein', None, '0504269464', 'pro@national-plastic.com', None),
	('NAJMAT AL WARQAA Documents Typing & Copying', 'Siddique', None, '0555450066', 'lukuballa@gmail.com', None),
	('NAZIH COSMETICS L L C S P - BRANCH 1', 'Abbas hussein', None, '+971 50 463 2396', 'pro@nazih.com', '100287633000003'),
	('NAZIH GROUP', 'Johnson Peter', None, '050 463 2396', 'nazihgroup@gmail.com', None),
	('AL NEEL Typing & Transalation Centre', 'Siddique', None, '0502351439', 'alneeltyping@gmail.com', None),
	('WAHAT AL NEJOUM  TYPING CENTER', 'Siddique', None, '0556399618', 'perfectvisacentre@gmail.com', None),
	('NEXT GENERATION TYPING CENTRE', 'Siddique', None, '05211202090', 'nazarulislamtravelagency@gmail.com', None),
	('Najamat Al Falah Typing & Photocopying', 'Mahmoud Nashaat', None, '065435771', 'alfalahsstar2011@gmail.com', None),
	('NOOR AL HAYAT Typing and Copying', 'Siddique', None, '0504800424', 'norhyatyping22@gmail.com', None),
	('NOOR AL BARAKAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0503636973', 'nooralbarakahtyping@gmail.com', None),
	('NOOR AL MADINAH TYPING CENTRE', 'Abbas hussein', None, '559058105', 'MADINAHTYPING@GMAIL.COM', None),
	('NOOR AL MANAKH TYPING & DOCUMENTS PHOTOCOPYING SERVICES', 'Siddique', None, '0564183087', 'nooralmanakh2025@gmail.com', None),
	('NOOR AL QAMAR DOCUMENTS TYPING & COPYING SERVICES', 'Siddique', None, '0502466010', 'habibkhattak98@gmail.com', None),
	('NOOR MAMZAR MEDICAL CENTRE', 'Abbas hussein', None, '+971 54 792 6533', 'mohamedibrahim5117@gmail.com', None),
	('NOORUDHEEN PRO', 'Siddique', None, '0556316156', 'Noorun076@gmail.com', None),
	('NOVA CLASSIC METALS TRADING LLC', 'Siddique', None, '0586105676', 'Pro-assistant@coremetal.net', None),
	('Al NADA Typing center', 'Siddique', None, '0562287216', 'alnadatyp@gmail.com', None),
	('AL NIBRAS AL THAHABI DOCUMENT TYPING AND COPYING', 'Siddique', None, '0556290748', 'nibrasthahabi@gmail.com', None),
	('BAREEQ AL NUJOOM TYPING AND DOCUMTS PHOTOCOPYING SERVICES', 'Siddique', None, '0557055758', 'typingnujoom@gmail.com', None),
	('Oxford Building Contracting L.L.C', 'Mahmoud Nashaat', None, '0504181256', 'oxford.contract@gmail.com', None),
	('OZONE BUSINESS MEN SERVICES', 'Siddique', None, '0555870007', 'ali@ozonebusiness.ae', None),
	('OCTOBER Typing', 'Siddique', None, '0507899865', 'octobertyping@gmail.com', None),
	('Oilfield Processing Center Limited', 'Aya Mostafa', None, '971504517140', None, None),
	('OMAR AL MUKHTAR Typing & Documents', 'Siddique', None, '0501647637', 'omartyping@gmail.com', None),
	('ON TIME Typing Services', 'Siddique', None, '0565067223', 'ontimetyping@outlook.com', None),
	('OXFORD Typing & Document Copying', 'Siddique', None, '0553226515', 'oxfordtyp@gmail.com', None),
	('MUNTHAHA PAINTS', 'Aya Mostafa', None, '0506796435', None, None),
	('Pando Building Maintenance / Pando Insulation Mat', 'Razan Samor', None, '0504807407', 'PANDOPROUAE@GMAIL.COM', None),
	('PEARLS BEAUTY LADIES SALOON', 'Jithin Raj', None, '0585256212', 'amisha.habeeb@gmail.com', None),
	('PLATINUM TYPING & DOCUMENT COPYING', 'Siddique', None, '0557867701', 'platinumtypinguae@gmail.com', None),
	('POWER PLUS BUSINESSMEN SERVICES', 'Siddique', None, '050577784', 'sharjah.business.setup@gmail.com', None),
	('PRE-EMPLOYEMENT MEDICAL', 'CZG Group', None, '+971 55 608 9051', 'accounts@altajcentre.ae', None),
	('PRIME DIGITAL BUSINESS SERVICES CO.L.L.C', 'Abbas hussein', None, '0568672320', 'primetypingdubai@gmail.com', None),
	('PRO JAMSHEER SYED', 'Rasheed', None, '055 5581867', 'jamsheersyed@gmail.com', None),
	('PRO LIGHT ELECT.IND.LLC', 'Mahmoud Nashaat', None, '0543065176', 'asifyousaf50@gmail.com', None),
	('PROFESSIONAL HAND Documents Clearing & Corporate Services', 'Abbas hussein', None, '0522600629', 'info@theprofessionalhand.com', None),
	('PROFESSIONAL SECURITY SYSTEMS', 'Saif sameh', None, '0558480985', None, None),
	('Al Qaryah Cars Auction', 'Noha', None, 'Ijaz Hayat', None, None),
	('QASR AL INJAZ TYPING AND DOCUMENTS PHOTO COPYING', 'Siddique', None, '0526287330', 'qasar.injaz@gmail.com', None),
	('QASR AL SHARQ TYPING AND COPYING', 'Siddique', None, '0509553715', 'info@qasarshj@gmail.com', None),
	('QAMR AL QASSIMIAH TYPING AND DOCUMENTS PHOTOCOPYING SERVICES', 'Siddique', None, '0589172844', 'qamaralqassimia@gmail.com', None),
	('QAMAR HOZAYRAN TECHNICAL SERVICES', 'Aya Mostafa', None, '0501465496', 'qamarhozayran@gmail.com', None),
	('QUALITY WORLD TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '000000', 'qualityworldtyping@gmail.com', None),
	('QUBAA Typing & Photocopying', 'Mahmoud Nashaat', None, '065669643', 'qubaac@yahoo.com', None),
	('QUICK GLOBAL TYPING DOCUMENTS', 'Siddique', None, '0509172310', 'quickglobaltyping@gmail.com', None),
	('Rafat Personal Customers', 'Aya Mostafa', None, '0569102021', 'Rafatazhari68@gmail.com', None),
	('Al Rahmah Typing & Document Copying', 'Mahmoud Nashaat', None, '0521852389', 'alrahmahtyping@gmail.com', None),
	('RABIE AL MADINAH TYPING & PHOTOCOPYING', 'Siddique', None, '0527030093', 'madeenatyping@gmail.com', None),
	('RAMZ AL RAHMANIAH TYPING & DOCUMENTATION COPYING', 'Siddique', None, '0523371916', 'ramzttdc2@gmail.com', None),
	('AL RAQI DOCUMENT TYPING & COPYING', 'Siddique', None, '0528390021', 'alraqidocuments@gmail.com', None),
	('RUKN AL RAYAN TYPING SERVICES', 'Siddique', None, '054 3115656', None, None),
	('Rashed Saeed Typing & Travels', 'Siddique', 'Shop No. 20 Zakhiem Building Opp. Side Citi Taxi Sharjah  UAE', '00971 58 153 3467', 'citytypingtravels@gmail.com', None),
	('RASHEED PRO', 'Siddique', None, '0522505913', 'Rasheed.malayil@coremetal.net', None),
	('RUKUN AL WAFA TYPING CENTRE', 'Aya Mostafa', None, '0523255088', 'ruknalwafa14@gmail.com', None),
	('Dr. Scent -RAWAIEH AL ZUHOR CLEANING & DETERGENT TR L L C', 'Razan Samor', None, '0529554004', 'Admin-assistant@dr-scent.com', None),
	('RAWDAT ALKAIR PROJECT MANAGMENT SERVICES', 'Mahmoud Nashaat', None, '0505595167', None, None),
	('AL RAYAN Document Clearance', 'Siddique', None, '0558685453', 'alrayandocument77@gmail.com', None),
	('REBOU AL ITEMAD TR.LLC', 'Siddique', None, '971 50 229 7204', 'hr1@aleatemad.ae', None),
	('Recruitment One Person Sawaed  Company LLC', 'Aya Mostafa', None, '971 503353343', None, None),
	('RED SEA HOUSING SERVICES COMPANY LLC', 'Siddique', None, '0521142480', 'Mohamed.ali@redseaintl.com', None),
	('REEH AL JANOOB BUILDING CLEANING SERVICES', 'Mohammad Hussein Hasan', None, '0506277116', None, None),
	('Al Reem Typing & Copying', 'Siddique', None, '971 50 539 2080', 'reemtyping@gmail.com', None),
	('Reham Typing Center', 'Abbas hussein', None, '0508600308', 'rehamtyping@gmail.com', None),
	('REMAL BUSINESSMEN SERVICES', 'Abbas hussein', None, '0506769791', 'remalbms1234@gmail.com', None),
	('RESALAT Typing', 'Siddique', None, '0559056300', 'resalatyping@gmail.com', None),
	('Revoli building cont. LLC', 'Mahmoud Nashaat', None, '0568383144', 'onfo@rivolibc.com', None),
	('Reyah Al Bahr Typing', 'Siddique', None, '+971 55 532 0036', 'reyahalb@gmail.com', None),
	('AL RIYADH Typing & Document Copying', 'Siddique', None, '0504105477', 'riyadtyping@gmail.com', None),
	('RASHED MOHAMMED ABDI DOCUMENT CLEARING', 'Siddique', None, '00971565656605', 'rashed.abdi@hotmail.com', None),
	('ROYAL WAY TAX CONSULTANCY', 'Abbas hussein', None, '0581604100', 'royalwayshj@gmail.com', None),
	('RRR DOCUMENTS CLEARING SERVICES CO.', 'Abbas hussein', None, '0556552414', 'rrrtyping@gmail.com', None),
	('RUBY Typing & Document Copying', 'Siddique', None, '06 5484830', 'rubygraphic@gmail.com', None),
	('RUKN AL MAROUF Typing & Copying Services', 'Siddique', None, '0561720029', 'maroufiqbal@yahoo.com', None),
	('RUKIN AL KHIBRAH Typing Document & Copying', 'Siddique', None, '065219373', 'mahmoodfida@gmail.com', None),
	('RUKN AL BATAEH TYPING AND DOCUMENTS COPYING', 'Siddique', None, '0564993921', 'ruknalbataehtyping@gmail.com', None),
	('RUKN AL IKHLAS TYPING & COPYING SERVICES', 'Abbas hussein', None, '0522739855', 'ruknalikhlastyping@gmail.com', None),
	('Rukn Al Irfad TYPING & DOCUMENTS COPYING', 'Siddique', None, '0523273249', 'ruknalirfadtyping@gmail.com', None),
	('RUKN AL MAJAZ DOCUMENTS TYPING AND COPYING', 'Mahmoud Nashaat', None, '97165698344', 'ruknalmajaz355@gmail.com', None),
	('RUKN AL NOOR Businessmen Services', 'Abbas hussein', None, '0503737598', 'info@ruknalnooruae.com', None),
	('RUKN AL RAMZ DOCUMENTS TYPING & COPYING', 'Siddique', None, '0503703041', 'ruknalramztyping@gmail.com', None),
	('RUKN AL RUAYA TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0547816916', 'ruknalruayatyping@gmail.com', None),
	('RUKN AL SALAMAH DOCUMENTS TYPING & COPYING', 'Siddique', None, '0502529322', 'contact@ruknalsalama.com', None),
	('RUKN AL TAJ BUSINESS MEN SERVICES', 'CZG Group', None, '+971 55 608 9051', 'accounts@altajcentre.ae', None),
	('RUKN AL TANSEEQ TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0555176787', 'tanseeq786@gmail.com', None),
	('RUKN AL TAREEQ TYPING & DOCUMENTS COPYING', 'Siddique', None, '0522992371', 'rtqtyping@gmail.com', None),
	('RUKN AL TASAHEEL', 'Siddique', None, '067043232', 'tasaheeltyping01@gmail.com', None),
	('RUKN AL TAWAR BUSINESS MEN SERVICES', 'Siddique', None, '0565573006', 'altawardhd@gmail.com', None),
	('RUKN QEMAT AL IBDAA KITCHENS & REST.EQUIP.TR L.L.C. SP', 'Abbas hussein', None, '+971501265860', None, None),
	('AL RUMAN Business men Service Centre', 'Siddique', None, '971564848184', 'rumantyping1@gmail.com', None),
	('Ruwad Al Khibrah Business Men Service LLC SP', 'Aya Mostafa', None, '0509764500', 'ammar@ruwadalkhibrah.com', None),
	('ROYAL WORLD TOURISM', 'Siddique', None, '0552097766', 'royalworldtourism@gmail.com', None),
	('AL SAAH Business Sevices', 'Siddique', None, '0503026765', 'alsaahb2021@gmail.com', None),
	('Sabah Group of companies', 'Aya Mostafa', None, '971 50 630 7041', 'bimal@sabahmetal.com', None),
	('SABAA TYPING CENTRE', 'Siddique', None, '0501420544', 'admin@sabaatyping.com', None),
	('AL SABEEL PVT REAL ESTATE MANAGMENT', 'Mahmoud Nashaat', None, '0503609182', 'masoom1972@gmail.com(Al Sabeel)', None),
	('Al Sadaqah Typing & Document Copying', 'Siddique', None, '0507700903', 'alamdubai@gmail.com', None),
	('Al SADDIQ IND  & TR CO LLC', 'Aya Mostafa', None, '0504998015', 'ahmed.a@aksadek.ae', None),
	('Al Safa Contracting LLC', 'Mahmoud Nashaat', None, '0555560261', 'alsafacontracting@gmail.com', None),
	('SAFA AL SHAMS TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0559495088', 'safaalshamstyping@gmail.com', None),
	('Safeena Group', 'Siddique', None, '0559300356', 'safinatypinglg@gmail.com', None),
	('AL SAFEER INT.LLC', 'Aya Mostafa', None, '971 56 993 0554', 'info.hr@safeergroup.com', '100301946800003'),
	('AL SAFINA Documents Typing & Copying', 'Siddique', None, '065661473', 'safinatyping@gmail.com', None),
	('Safu Typing & Travels', 'Abbas hussein', None, '0563036747', 'travelssafu@gmail.com', None),
	('Al Safwah Oil Fields Supply LLC', 'Siddique', None, '+971 56 704 0786', 'hajinawaz786pk@gmail.com', None),
	('Al Sagar National Insurance CO. (PSC)', 'Aya Mostafa', None, '+971 56 996 6164', None, None),
	('SAHAM AL INJAZ TYPING CENTRE', 'Siddique', None, '567866443', 'SAHAM.TS2024@GMAIL.COM', None),
	('SAHARA TRAVELS & STUDIO', 'Siddique', None, '0557867701', 'saharatyping22@gmail.com', None),
	('SAHARA BEACH RESORT &SPA SHARJAH.L.L.C - S.P', 'Abbas hussein', None, '0562805706', 'pro@aryanahotels.com', None),
	('SAHARA TYPING BR2', 'Abbas hussein', None, '0529806860', 'typsahara@gmail.com', None),
	('AL SAHEEL Typing & Document Copying', 'Siddique', None, '065512110', 'alsaheerbr1@gmail.com', None),
	('AL SAHEEL (2010) TYPING', 'Siddique', None, '0509618340', 'alsaheel2010@gmail.com', None),
	('SAHM ALBHAR MEDICAL EQUIPMENT', 'Mahmoud Nashaat', None, '0566114060', None, None),
	('SALIH PRO', 'Siddique', None, '0501196131', 'SALEHKHAN505@GMAIL.COM', None),
	('SALMAN AL FARSI SCHOOL', 'Mahmoud Nashaat', None, '0567953705', None, None),
	('SALSABIL DOCUMENTS TYPING AND COPYING', 'Mahmoud Nashaat', None, '0504765634', 'salsabiltyping@yahoo.com', None),
	('SAMA AL MADINAH TYPING AND COPYING', 'Abbas hussein', None, '0563944186', 'amalik466@gmail.com', None),
	('AL SAMAH Typing & Document Copying', 'Siddique', None, '0503034848', 'alsamah2000@gmail.com', None),
	('AL SAMAMAH Doument Typing & Copying', 'Siddique', None, '065669811', 'alsamamah786@gmail.com', None),
	('SAQER AL YERMOUK BUSINESS MEN SERVICES', 'Siddique', None, '0504886300', 'saqralearmouk@gmail.com', None),
	('SAQR AL SAEED TYPING AND COPYING SERVICES', 'Siddique', None, '0555775183', 'essamriyadh100@gmail.com', None),
	('SHAMS AL ROLLA TYPING SERVICES', 'Siddique', None, '0503596024', 'alrollatyping@gmail.com', None),
	('SARA ALI DOCUMENTS TYPING & COPYING', 'Siddique', None, '0509628292', 'saraalityping933@gmail.com', None),
	('Sarah Plaza Trading Company LLC Branch', 'Aya Mostafa', None, '971 551272001', None, None),
	('SATNAM SINGH PRO', 'Siddique', None, '0509882472', 'dubaiwala345@gmail.com', None),
	('STARS GROUPS', 'Aya Mostafa', None, '0501810488', 'mostafa@starsaluminium.com', None),
	('SAWAEED EMPLOYMENT SOLE PROPRIETORSHIP L L C - DUBAI BRANCH', 'Dina Ablan', None, '971-56-5259973', 'Munir.idriss@sawaeedemployment.com', None),
	('SKY BLUE BUSINESSMEN SERVICES', 'Mahmoud Nashaat', None, '97165795937', 'sky.blue10178@gmail.com', None),
	('Scaform people', 'Aya Mostafa', None, '971 562223586', None, None),
	('Shams Customer Servicing LLC', 'CZG Group', None, '0526402776', 'omair@smsemail.co', None),
	('SEDAR DECOR FACTORY L.L.C', 'AL TAJ', None, '0501415707', 'MUSLIM@SEDARGLOBAL.COM', None),
	('SEDNY TYPING & DOCUMENT COPYING', 'Siddique', None, '0555167696', 'typingsedny@gmail.com', None),
	('BAB SEENA TYPING DOCUMENTS & COPYING', 'Siddique', None, '0567800332', 'bstdc2022@gmail.com', None),
	('Seher Albarq Technical And Cleaning Services', 'Noha', None, '0544382621', 'seheralbarq@gmail.com', None),
	('Al Serh Alkabeer Constuctions.', 'Mahmoud Nashaat', None, '971552260350', 'pro@alserhgroup.com', None),
	('Shafeeq Clients', 'Aya Mostafa', None, '06035001', None, None),
	('AL SHAHD Typing & Documents Copying', 'Siddique', None, '067678500', 'alshahdtyping@gmail.com', None),
	('AL SHAHID Typing & Document Copying', 'Siddique', None, '0509955429', 'alshahidtyping@gmail.com', None),
	('Shajahan  PRO', 'Siddique', None, '0526357470', 'shajahanshaja294@gmail.com', None),
	('SHAMS AL BAHR DOCUMENTS TYPING & COPYING', 'Abbas hussein', None, '0566661531', 'shamsalbahrtyp@gmail.com', None),
	('SHAMS AL KHAN TYPING DOCUMENTS COPYING', 'Siddique', None, '0551852595', 'shamsalkhantyping@gmail.com', None),
	('SHAMS MUWAILEH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0564611560', 'shamsityping@gmail.com', None),
	('AL SHAMS AND AL QAMAR DOCUMENTS TYPING & COPYING', 'Siddique', None, '065677005', 'alqamartc@gmail.com', None),
	('Sharjah Media City - Freezone Authority', 'CZG Group', None, '+971 55 403 3010', 'mustafa.hashmi@shamsfz.ae', None),
	('SHARUKH PRO', 'Siddique', None, '0558274645', 'Sharukh.siddique@irc.ae', None),
	('SHATEE ALBAHAR  DOCUMENTS TYPING & COPYING', 'Siddique', None, '0545010453', 'shateealbahartyping@gmail.com', None),
	('AL SHAZA Typing', 'Mahmoud Nashaat', None, '0529090658', 'alshaza2@yahoo.com', None),
	('SHAZIL FOR ARTISTIC TALENT CONTRACTING', 'Mohammad Hussein Hasan', None, '0543223736', 'Companysetup3@gmail.com-SHAZIL', None),
	('Sherrif albaghdady contracting l l c', 'Noha', None, '0558016325', 'acc_ghanem@hotmail.com', None),
	('SHIBU PERSONAL CUSTOMERS (PRO)', 'Siddique', None, '0507562485', 'shibu.josephnielseniq.com', None),
	('sharjah collection hotel managment', 'Mahmoud Nashaat', None, '0555577871', None, None),
	('Sharjah Islamic Bank', 'Mahmoud Nashaat', None, '0505293788', 'sharjahislamicbank@gmail.com', None),
	('Siddique Peronal Customer', 'Siddique', None, '0552936524', None, None),
	('SIGNATURE TYPING SERVICES', 'Siddique', None, '0504271285', 'signaturetyp@gmail.com', None),
	('SILVAR HOME REAL ESTATE', 'Siddique', None, '06 5756780', 'regencytower1@gmail.com', None),
	('SILVER LINE PRINTING MAT.TR.LLC', 'Siddique', None, '0505259264', 'SILVERSTRDUBAI@GMAIL.COM', None),
	('SILVER STAR PRINTING MATIERIALS TRADING LLC', 'Siddique', None, '0561293728', 'SHAFIYE@GMAIL.COM', None),
	('SKILLS HUB DELIVERY SERVICES L.L.C', 'Mahmoud Nashaat', None, '0563293984', 'syed.owais@skillshub.ae', None),
	('Sky Gate Typing', 'Siddique', None, '0589402244', 'skygaetyping@gmail.com', None),
	('SKYBOUND TRAVELS', 'Siddique', None, '0561847873', 'SKYBOUNDTRAVELS2@GMAIL.COM', None),
	('SMART LIFE TYPING SERVICES', 'Siddique', None, '0502290133', 'smartlifetyping@gmail.com', None),
	('SRI LANKA AUTO', 'Johnson Peter', None, '050 806 1069', 'srilankaauto@gmail.com', None),
	('SMART POINT Business Service', 'Siddique', None, '0558902401', 'smartpointbusinessmen@gmail.com', None),
	('Smart Care Tr.', 'Abbas hussein', None, '0556841579', 'services@smartcaretr.info', None),
	('Smart Galaxy', 'Mahmoud Nashaat', None, '971 55 602 4711', None, None),
	('SMART TRIP TYPING & DOCUMENTS COPYING', 'Siddique', None, '0562043786', 'smarttrip.typing786@gmail.com', None),
	('SMART WAY Typing', 'Siddique', None, '0554558622', 'typingsmartway@gmail.com', None),
	('SMARTWINGS TYPING AND DOCUMENT CENTER', 'Siddique', None, '0563089515', 'smartwingsbr1@gmail.com', None),
	('Shams Management Services', 'CZG Group', None, '052 6402776', 'waqas@smsemail.co', None),
	('Solico fiber Glass factor', 'Mahmoud Nashaat', None, '0505270712', 'noriel@solicotanks.com', None),
	('SPC MANAGEMENT SERVICES FZC', 'CZG Group', 'Business Center, Sharjah Publishing City Free Zone, Sharjah, Sharjah, United Arab Emirates, 0000, +97165545512', '055 2326256', 'harshil@spcfz.ae', None),
	('SPEED POINT Typing Center', 'Mahmoud Nashaat', None, '0566866799', 'info@speedpointtypingcenter.com', None),
	('SPEED WAY TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0508531423', 'speedway2023@gmail.com', None),
	('Speedway  Typing Business Men Services', 'Siddique', None, '0527864568', 'speedwaytype@gmail.com', None),
	('SPICE GOURMET RESTAURANTL.L.C', 'Gehad', None, '12345678', 'spicegrillshj@gmail.com', None),
	('SPICE GRILL SEAFOOD RESTAURANT L.L.C', 'Gehad', None, '0508020291', None, None),
	('SPRINGFIELD TRAVEL & TOURISM LLC', 'Siddique', None, '0543350719', 'info@springfieldtyping.com', None),
	('Shams Services LLC', 'CZG Group', None, '971 0502482062', 'arun@smsemail.co', None),
	('AL NAJM AL MUSHRIQ Typing & Documents  Copying', 'Siddique', None, '0505039688', 'stars.typing@gmail.com', None),
	('STEEL CRAFT ENGINEERING', 'Siddique', None, '0586105676', 'Pro-assistant@coremetal.net', None),
	('SUNDERILA Typing Center', 'Siddique', None, '0563433435', 'sunderila@gmail.com', None),
	('TAASIS Privet Companies Management Service', 'Abbas hussein', None, '0555541336', 'ceo@taasis.ae', None),
	('TABA Typing & Document Copying', 'Siddique', None, '065755277', 'tabauae@gmail.com', None),
	('TABREEZ Corporate service advisor', 'Abbas hussein', None, '0565227266', 'info@tabreez.ae', None),
	('TABSEET BUSINESSMEN SERVICES', 'Siddique', None, '0502402540', 'tabseet01@gmail.com', None),
	('TADBEER SERVICES', 'CZG Group', None, '0565064765', 'accounts@altajcentre.ae', None),
	('TAFDEEL BUSINESS MEN SERVCES', 'Siddique', None, '065106799', 'tafdeel2021@gmail.com', None),
	('Tafheel', 'Siddique', 'Al Majaz 2 Jamal Abdul Nasir Street Sharjah UAE', '00971 58 8306644', 'hashim@tafheel.com', None),
	('AL TAISEER Businessmen Services', 'Siddique', None, '065251111', 'taiseerid@gmail.com', None),
	('TAJ Typing & Document Copying', 'Siddique', None, '0547891969', 'tajtyping@gmail.com', None),
	('TAJ AL YASMIN BUSSINESMEN SERVICES', 'Siddique', None, '0503330786', 'TAJALYASMINBS@GMAIL.COM', None),
	('TAJ ALI TYPING & DOCUMENTS COPYING', 'Siddique', None, '0562115574', 'tajalityping2022@gmail.com', None),
	('AL TAJ Management Consultancy', 'Siddique', None, '0097165620671', 'altajmc@gmail.com', None),
	('TAJEEL BUSINESS MANAGEMENT', 'Siddique', None, '0551414024', 'tajeeltyping@gmail.com', None),
	('TAKUMI BUSINESSMEN SERVICES SPC LLC', 'Siddique', None, '0542921372', 'takumibms@gmail.com', None),
	('TAREEQ AL MADINA businessmen services', 'Siddique', None, '0588350205', 'almadinabs2023@gmail.com', None),
	('Tareeq AL NOOR Typing & Document Copying', 'Siddique', None, '+971 50 155 4575', 'tareeqalnoortyp1@gmail.com', None),
	('TANJA TYPING CENTRE', 'Siddique', None, '0506262065', 'tanjatyping@yahoo.com', None),
	('Tanzeel Typing & Copying', 'Siddique', None, '971 52 4796163', 'tanzeel@tabascouae.com', None),
	('TAREEQ AL QASIMIAH Typing & Copying', 'Siddique', None, '0561882467', 'tareeqalqasimiah@gmail.com', None),
	('TAQDEEM Documents & Businessmen Services', 'Siddique', None, '06546364', 'taqdeemtyping@gmail.com', None),
	('Tareef Typing & Docum. Copying', 'Siddique', None, '971 58 620 9595', 'tareeftyping1@gmail.com', None),
	('TAREEQ AL QURAM TYPING & DOCUMENTS  COPYING', 'Abbas hussein', None, '0564798441', 'faizatravls@gmail.com', None),
	('TAREEQ KHAIBER  Documents Typing Copying', 'Siddique', None, '0544771865', 'tareeqkb@gmail.com', None),
	('AL TARTEEB DOCUMENTS TYPING & COPYING', 'Siddique', None, '0544363933', 'zaid.tarteeb@gmail.com', None),
	('TAREEQ AL NASAR Documents Typing & Copying', 'Siddique', None, '065251477', 'tareeqalnasrtyping@gmail.com', None),
	('TASHEEL Consultancy', 'Siddique', None, '0509792833', 'sharjah@tasheelconsultancy.com', None),
	('SHAMSU (TASHEEL NAZRIYA) - PRO Services', 'Siddique', None, '0507393179', 'shamsuck.116@gmail.com', None),
	('AL TASHKEEL Typing & Copying Documents', 'Siddique', None, '0559632666', 'altashkeeltyping@gmail.com', None),
	('TASLEEM - Business Men Services', 'Siddique', None, '971569728731', 'TASLEEMVISA@GMAIL.COM', None),
	('TAREEQ AL SAHIL typing and document copying', 'Mahmoud Nashaat', None, '0555594055', 'tareeqalsahil2022@gmail.com', None),
	('TAWASL TYPING & DOCUMENTS COPYING SERVICES L.L.C. SP', 'Siddique', None, '0505717556', 'tawasltyping@gmail.com', None),
	('AL TAWQIE AL THAHABI BUSINESSMEN SERVICES', 'Siddique', None, '+971566448809', None, None),
	('TAWWQET TYPING & DOCUMENTS COPYING', 'Siddique', None, '0563863372', 'amertawwqet2024@gmail.com', None),
	('TEXAS Bussines men services', 'Siddique', None, '065662333', 'info@texasbs.ae', None),
	('TOP GRADE TYPING', 'Abbas hussein', None, '0555640252', 'topgrade@gmail.com', None),
	('THAHAB AL ASFAR TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0508721509', 'tahabasfar@gmail.com', None),
	('THE DISTRICT VENUE READYMADE GARMENTS TRADING LLC', 'Siddique', None, '0528544378', 'Email-navasrj786@gmail.com', None),
	('THE PET SHOP L.L.C. - SHJ.BR 1', 'Aya Mostafa', None, '0563285417', 'may@thepetshop.com', None),
	('TIBO GRAPHIC TYPING & DOCUMENT COPYING', 'Siddique', None, '0507564992', 'a5738244@gmail.com', None),
	('TIBR DOCUMENTS CLEARING SERVICES LLC', 'Mahmoud Nashaat', None, '0551261554', 'tibrdocuments@gmail.com', None),
	('Tiger Contracting Co. LLC', 'Mahmoud Nashaat', None, '0503609182', 'masoom1972@gmail.com', None),
	('Tiger Industries LLC', 'Mahmoud Nashaat', None, '0503609182', 'masoom1972@gmail.com(Tiger Industries)', None),
	('TIMELINE BUSSINESMEN SERVICES', 'Siddique', None, '0561654391', 'timelineshj@gmail.com', None),
	('TAREEQ AL NUKHBAH DOCUMENTS TYPING & COPYING L.L.C.SP', 'Mohammad Hussein Hasan', None, '06 562 9066', 'tareq.alnukhba@gmail.com', None),
	('TOP WAY Typing & Documents Photocopying Services', 'Abbas hussein', None, '0524882792', 'topwaytyping@gmail.com', None),
	('TOPMAIDS CLEANING SERVICES', 'Mahmoud Nashaat', None, '0588288037', None, None),
	('Toy world distributor l l c', 'Noha', None, '123456', None, None),
	('trustway typing center', 'Siddique', None, '066780675', 'trustwaydoc@gmail.com', None),
	('AL TAHEEL Typing services', 'Siddique', None, '0507465800', 'taheeltyping@gmail.com', None),
	('TURBO SAREA DELIVERY SERVICES L.L.C', 'Abbas hussein', None, '+971 58 694 9432', 'Abdelhalim.turbo@gmail.com', '104896541000003'),
	('AL TAJ TYPIST / FRONT END DESK', 'CZG Group', None, '0506801964', None, None),
	('United Arab Bank', 'Mahmoud Nashaat', None, '0567006449', 'hcmgr@uab.ae', None),
	('velocity', 'Nikhil Raj', None, '+971 552299321', 'subair@velocitydxb.com', None),
	('VISION PRO TYPING SERVICES', 'Siddique', None, '971 54 409 6439', 'sales@visionprouae.com', None),
	('WADI KHAIBER TYPING & DOCUMENTS COPYING', 'Siddique', None, '0522627750', 'wadikhaibartyping@gmail.com', None),
	('WAQT AL FAJR Document Typing', 'Siddique', None, '0543657497', 'waqatalfajr.typ@gmail.com', None),
	('DAR AL WAFA DOCUMENTS TYPING & COPYING', 'Siddique', None, '0529466913', 'daralwafa430@gmail.com', None),
	('WAHAT AL MUSTAQBAL TYPING SERVICES', 'Siddique', None, '0502026940', 'smsmobile104@gmail.com', None),
	('WAHAT AL WAFA Typing & Documents Copying', 'Siddique', None, '0554932987', 'wafatypingshj@gmail.com', None),
	('AL WALAA Typing & Document Copying', 'Siddique', None, '0526617424', 'alwalatyping@yahoo.com', None),
	('WALEED AL ALI GROUP', 'Siddique', None, '0547868855', None, None),
	('Walk-in Customer', None, None, '12345678900', None, None),
	('WAHAT AL MANARAH Typing and Document Copying', 'Siddique', None, '065732080', 'wahatalmanarah@gmail.com', None),
	('WAHAT AL NAHDA TYPING & DOCUMENT COPYING', 'Siddique', 'wahatalnahdatyping@gmail.com', '0527562895', None, None),
	('WASAT AL QASMIAH TYPING & DOCUMENTS COPYING', 'Siddique', None, '0529240871', 'wasatalqasmiahtyping@gmail.com', None),
	('WASCO Typing & Document Copying', 'Siddique', None, '065731986', 'wascotyping@gmail.com', None),
	('Al Wasit Document Typing & Copying', 'Siddique', None, '0561818108', 'saleem@wasit.ae', None),
	('AL WAZEER TYPING CENTER', 'Siddique', None, '065663308', 'wazeer@gmail.com', None),
	('White Cloud Typing & Documents Copying', 'Abbas hussein', None, '0507310515', 'istan332@gmail.com', None),
	('WADI AL KHAIR Typing & Document', 'Siddique', None, '97167678474', 'alkhairtyping@gmail.com', None),
	('WORD PRO BUSINESS MANAGEMENT SERVICES', 'Siddique', None, '0527608973', 'info@wordpro.ae', None),
	('Wahat Al Rawahil Business Men Services Br.3', 'Siddique', None, '0503907861', 'wahatalrawahil@gmail.com', None),
	('AL WUROOD TYPING CENTER', 'Siddique', None, '0554445128', 'alwuroodtyping@gmail.com', None),
	('YAAQOOB PRO', 'Mahmoud Nashaat', None, '50 1069104', 'yaaqoobpro@gmail.com', None),
	('AL YASEEN TYPING SERVICES Branch 1', 'Siddique', None, '0502421614', 'yaseentyping2010@gmail.com', None),
	('Al Yash Typing Services', 'Siddique', None, '971 52 940 9424', 'alyashtyping@mail.com', None),
	('DAR AL ZAEEM TYPING & DOCUMENTS COPYING', 'Mahmoud Nashaat', None, '0563331065', 'alzaeem.typing2022@gmail.com', None),
	('ZAFAR IQBAL DECOR CONTRACTING', 'Siddique', None, '0558525566', None, None),
	('AL ZAHI International Business Consultancy', 'Siddique', None, '971558196977', 'medical.alzahi@gmail.com', None),
	('ZAHRA FADHIAH TYPING & DOCUMENTS COPYING', 'Abbas hussein', None, '0545204320', 'zahrafadhiah@gmail.com', None),
	('Zahart Al Qasimiah', 'Siddique', None, '065104698', 'zaharat.qasmiah@gmail.com', None),
	('Zahrat Al Nouf Typing & Documents Copying', 'Abbas hussein', None, '0568614576', 'zahrattypingcenter@gmail.com', None),
	('ZAHRAT AL RABIE DOCUMENTS TYPING AND COPYING', 'Mahmoud Nashaat', None, '0509378121', 'alrabeehdocs@gmail.com', None),
	('ZAID PRO', 'Aya Mostafa', None, '0562297729', None, None),
	('AL ZAKHIR Documents Typing', 'Mahmoud Nashaat', None, '0527700312', 'zakhirtyping@gmail.com', None),
	('Ziad Document Copying', 'Mahmoud Nashaat', None, '0506260223', 'zouz1957@gmail.com', None),
)


def run(dry_run=0):
	"""Create the PRO customers, then the client companies linked to them.

	:param dry_run: report what would happen without writing.
	"""
	dry_run = cint(dry_run)

	pros_created, pros_existing, problems = [], [], []

	for pro in PROS:
		if frappe.db.exists("Customer", pro):
			pros_existing.append(pro)
			continue

		if not dry_run:
			try:
				frappe.get_doc(
					{
						"doctype": "Customer",
						"customer_name": pro,
						"customer_type": "PRO",
						"customer_group": CUSTOMER_GROUP,
					}
				).insert(ignore_permissions=True)
			except Exception as error:
				problems.append(("PRO", pro, short(error)))
				continue

		pros_created.append(pro)

	if not dry_run:
		frappe.db.commit()

	# Continue the existing numbering rather than restarting it.
	next_company_id = highest_company_id() + 1

	clients_created, clients_existing, unlinked = [], [], []

	# PRO records that exist, or would exist after a real run. Keyed lower so a
	# difference in casing between the two columns still links.
	available_pros = {p.lower(): p for p in list(pros_created) + list(pros_existing)}

	for name, pro, address, mobile, email, trn in CLIENTS:
		if frappe.db.exists("Customer", name):
			clients_existing.append(name)
			continue

		email, bad_email = clean_email(email)

		if bad_email:
			problems.append(("email dropped", name, bad_email))

		link, reason = resolve_pro(name, pro, available_pros)

		if not link:
			unlinked.append((name, reason))

		if dry_run:
			clients_created.append(name)
			next_company_id += 1
			continue

		try:
			frappe.get_doc(
				{
					"doctype": "Customer",
					"customer_name": name,
					"customer_type": "Company",
					"customer_group": CUSTOMER_GROUP,
					# Set explicitly so before_save neither renumbers it nor
					# pushes the customer to the external service.
					"company_id": next_company_id,
					"pro_customer": link,
					"address_line_1": address,
					"mobile_no": mobile,
					"email_id": email,
					"tax_id": trn,
				}
			).insert(ignore_permissions=True)
		except Exception as error:
			problems.append(("Company", name, short(error)))
			continue

		clients_created.append(name)
		next_company_id += 1

	if not dry_run:
		frappe.db.commit()

	report(pros_created, pros_existing, clients_created, clients_existing, unlinked, problems, dry_run)

	return {
		"pros_created": pros_created,
		"pros_existing": pros_existing,
		"clients_created": clients_created,
		"clients_existing": clients_existing,
		"unlinked": unlinked,
		"problems": problems,
		"dry_run": bool(dry_run),
	}


def clean_email(email):
	"""(usable email, rejected value). Keeps the customer when the email is bad."""
	if not email or EMAIL_PATTERN.match(email):
		return email, None

	return None, email


def resolve_pro(name, pro, available_pros):
	"""(pro to link, reason it could not be linked)."""
	if not pro:
		return None, "no P.R.O Name in the sheet"

	# A client who is their own PRO cannot link to itself: the record carries a
	# single customer_type, and self reference is rejected by validation.
	if pro.lower() == name.lower():
		return None, "is their own PRO"

	found = available_pros.get(pro.lower())

	if not found:
		return None, f"no PRO record for '{pro}'"

	return found, None


def highest_company_id():
	"""The largest company_id in use, so new ones continue the sequence."""
	return cint(frappe.db.sql("select max(company_id) from `tabCustomer`")[0][0])


def short(error):
	return f"{type(error).__name__}: {str(error)[:90]}"


def report(pros_created, pros_existing, clients_created, clients_existing, unlinked, problems, dry_run):
	verb = "[dry run] would create" if dry_run else "created"

	print("\nCustomer seed")
	print(f"  PRO customers    : {len(PROS)} defined, {verb} {len(pros_created)}, present {len(pros_existing)}")
	print(f"  Client companies : {len(CLIENTS)} defined, {verb} {len(clients_created)}, present {len(clients_existing)}")
	print(f"  without a PRO    : {len(unlinked)}")
	print(f"  problems         : {len(problems)}")

	for name, reason in unlinked[:20]:
		print(f"    ~ {name} -- {reason}")

	for kind, name, reason in problems[:20]:
		print(f"    ! {kind} {name}: {reason}")
